/**
 * Icon lookup: Simple Icons (SVG) → Google Favicon (real logo) → colored letter
 */

// Explicit domain map for services where the domain isn't obvious from the name
const DOMAIN_MAP: Record<string, string> = {
  // --- Streaming ---
  'netflix': 'netflix.com',
  'disney+': 'disneyplus.com',
  'hulu': 'hulu.com',
  'prime video': 'primevideo.com',
  'amazon prime video': 'primevideo.com',
  'apple tv+': 'tv.apple.com',
  'youtube premium': 'youtube.com',
  'max (hbo)': 'max.com',
  'hbo max': 'max.com',
  'peacock': 'peacocktv.com',
  'paramount+': 'paramountplus.com',
  'crunchyroll': 'crunchyroll.com',
  'espn+': 'espn.com',
  'starz': 'starz.com',
  'amc+': 'amcplus.com',
  'shudder': 'shudder.com',
  'britbox': 'britbox.com',
  'acorn tv': 'acorn.tv',
  'criterion channel': 'criterionchannel.com',
  'youtube tv': 'tv.youtube.com',
  'sling tv': 'sling.com',
  'fubotv': 'fubo.tv',
  'philo': 'philo.com',
  'mubi': 'mubi.com',
  'vimeo': 'vimeo.com',
  'curiositystream': 'curiositystream.com',
  'crave': 'crave.ca',
  'sky': 'sky.com',
  'now': 'nowtv.com',
  'canal+': 'canalplus.com',
  'joyn+': 'joyn.de',
  'rtl+': 'rtlplus.com',
  'viaplay': 'viaplay.com',
  'skyshowtime': 'skyshowtime.com',
  'stan': 'stan.com.au',
  'binge': 'binge.com.au',
  'kayo sports': 'kayosports.com.au',
  'neon nz': 'neontv.co.nz',
  'viu': 'viu.com',
  'twitch turbo': 'twitch.tv',
  'kick': 'kick.com',
  'filmin': 'filmin.es',

  // --- Music ---
  'spotify': 'spotify.com',
  'apple music': 'music.apple.com',
  'youtube music': 'music.youtube.com',
  'tidal': 'tidal.com',
  'amazon music': 'music.amazon.com',
  'deezer': 'deezer.com',
  'soundcloud go+': 'soundcloud.com',
  'pandora': 'pandora.com',
  'qobuz': 'qobuz.com',
  'siriusxm': 'siriusxm.com',
  'tunein premium': 'tunein.com',
  'kkbox': 'kkbox.com',
  'joox': 'joox.com',
  'gaana': 'gaana.com',
  'jiosaavn': 'jiosaavn.com',
  'wynk music': 'wynk.in',
  'boomplay': 'boomplay.com',
  'anghami': 'anghami.com',

  // --- Podcasts ---
  'audible': 'audible.com',
  'scribd/everand': 'scribd.com',
  'storytel': 'storytel.com',
  'bookbeat': 'bookbeat.com',
  'nextory': 'nextory.com',
  'podimo': 'podimo.com',
  'luminary': 'luminary.link',

  // --- Sports ---
  'dazn': 'dazn.com',
  'the athletic': 'theathletic.com',
  'draftkings': 'draftkings.com',
  'fanduel': 'fanduel.com',

  // --- AI ---
  'chatgpt plus': 'openai.com',
  'chatgpt pro': 'openai.com',
  'claude pro': 'claude.ai',
  'claude max': 'claude.ai',
  'gemini advanced': 'gemini.google.com',
  'microsoft copilot pro': 'copilot.microsoft.com',
  'perplexity pro': 'perplexity.ai',
  'poe': 'poe.com',
  'midjourney': 'midjourney.com',
  'dall-e': 'openai.com',
  'leonardo.ai': 'leonardo.ai',
  'runway ml': 'runwayml.com',
  'pika': 'pika.art',
  'sora': 'openai.com',
  'synthesia': 'synthesia.io',
  'heygen': 'heygen.com',
  'elevenlabs': 'elevenlabs.io',
  'suno ai': 'suno.com',
  'udio': 'udio.com',
  'jasper ai': 'jasper.ai',
  'copy.ai': 'copy.ai',
  'grammarly premium': 'grammarly.com',
  'deepl pro': 'deepl.com',
  'otter.ai': 'otter.ai',
  'fireflies.ai': 'fireflies.ai',
  'descript': 'descript.com',
  'notion ai': 'notion.so',

  // --- Developer ---
  'github pro': 'github.com',
  'github copilot': 'github.com',
  'gitlab premium': 'gitlab.com',
  'jetbrains all products': 'jetbrains.com',
  'replit': 'replit.com',
  'codesandbox': 'codesandbox.io',
  'gitpod': 'gitpod.io',
  'postman': 'postman.com',
  'docker pro': 'docker.com',
  'gitkraken': 'gitkraken.com',
  'cursor pro': 'cursor.com',
  'windsurf / codeium': 'codeium.com',
  'tabnine': 'tabnine.com',
  'claude code': 'claude.ai',
  'devin': 'cognition.ai',
  'vercel pro': 'vercel.com',
  'netlify pro': 'netlify.com',
  'railway': 'railway.com',
  'render': 'render.com',
  'heroku': 'heroku.com',
  'fly.io': 'fly.io',
  'digitalocean': 'digitalocean.com',
  'supabase': 'supabase.com',
  'planetscale': 'planetscale.com',
  'neon': 'neon.tech',
  'mongodb atlas': 'mongodb.com',
  'cloudflare': 'cloudflare.com',
  'sentry': 'sentry.io',
  'datadog': 'datadoghq.com',
  'new relic': 'newrelic.com',
  'leetcode': 'leetcode.com',
  'hackerrank': 'hackerrank.com',
  'tailscale': 'tailscale.com',

  // --- Productivity ---
  'microsoft 365': 'microsoft365.com',
  'google workspace': 'workspace.google.com',
  'notion': 'notion.so',
  'obsidian sync': 'obsidian.md',
  'roam research': 'roamresearch.com',
  'bear pro': 'bear.app',
  'ulysses': 'ulysses.app',
  'craft': 'craft.do',
  'heptabase': 'heptabase.com',
  'evernote': 'evernote.com',
  'day one': 'dayoneapp.com',
  'standard notes': 'standardnotes.com',
  'coda': 'coda.io',
  'airtable': 'airtable.com',
  'trello': 'trello.com',
  'asana': 'asana.com',
  'monday.com': 'monday.com',
  'jira': 'atlassian.com',
  'linear': 'linear.app',
  'clickup': 'clickup.com',
  'basecamp': 'basecamp.com',
  'confluence': 'atlassian.com',
  'todoist pro': 'todoist.com',
  'raycast pro': 'raycast.com',
  'setapp': 'setapp.com',
  'textexpander': 'textexpander.com',
  'superhuman': 'superhuman.com',
  'toggl track': 'toggl.com',
  'fantastical': 'flexibits.com',
  'calendly': 'calendly.com',
  'cal.com': 'cal.com',
  'reclaim.ai': 'reclaim.ai',
  'ifttt': 'ifttt.com',
  'zapier': 'zapier.com',
  'make': 'make.com',
  'wps office': 'wps.com',
  'goodnotes': 'goodnotes.com',
  'miro': 'miro.com',
  'loom': 'loom.com',

  // --- Design ---
  'adobe creative cloud': 'adobe.com',
  'adobe photoshop': 'adobe.com',
  'adobe lightroom': 'adobe.com',
  'adobe premiere pro': 'adobe.com',
  'adobe illustrator': 'adobe.com',
  'adobe after effects': 'adobe.com',
  'figma': 'figma.com',
  'figjam': 'figma.com',
  'canva pro': 'canva.com',
  'sketch': 'sketch.com',
  'framer': 'framer.com',
  'whimsical': 'whimsical.com',
  'lucidchart': 'lucid.app',
  'spline': 'spline.design',
  'sketchup': 'sketchup.com',
  'capcut pro': 'capcut.com',
  'davinci resolve studio': 'blackmagicdesign.com',
  'pixelmator pro': 'pixelmator.com',
  'affinity v2': 'affinity.serif.com',
  'shutterstock': 'shutterstock.com',
  'getty images': 'gettyimages.com',
  'adobe stock': 'stock.adobe.com',
  'istock': 'istockphoto.com',
  'envato elements': 'elements.envato.com',
  'artlist': 'artlist.io',
  'epidemic sound': 'epidemicsound.com',
  'storyblocks': 'storyblocks.com',
  'unsplash+': 'unsplash.com',

  // --- Cloud ---
  'icloud+': 'icloud.com',
  'google one': 'one.google.com',
  'dropbox plus': 'dropbox.com',
  'onedrive': 'onedrive.live.com',
  'google drive': 'drive.google.com',
  'pcloud': 'pcloud.com',
  'mega': 'mega.nz',
  'tresorit': 'tresorit.com',
  'backblaze': 'backblaze.com',
  'proton drive': 'proton.me',

  // --- VPN / Security ---
  'nordvpn': 'nordvpn.com',
  'expressvpn': 'expressvpn.com',
  'surfshark': 'surfshark.com',
  'protonvpn': 'protonvpn.com',
  'mullvad vpn': 'mullvad.net',
  '1password': '1password.com',
  'bitwarden premium': 'bitwarden.com',
  'dashlane': 'dashlane.com',
  'lastpass premium': 'lastpass.com',
  'norton 360': 'norton.com',
  'bitdefender': 'bitdefender.com',
  'experian': 'experian.com',
  'lifelock': 'lifelock.com',
  'myfico': 'myfico.com',
  'aura': 'aura.com',
  'proton unlimited': 'proton.me',

  // --- Communication ---
  'slack pro': 'slack.com',
  'zoom': 'zoom.us',
  'microsoft teams': 'teams.microsoft.com',
  'discord nitro': 'discord.com',
  'telegram premium': 'telegram.org',
  'whatsapp': 'whatsapp.com',
  'signal': 'signal.org',

  // --- Email ---
  'proton mail plus': 'proton.me',
  'hey': 'hey.com',
  'fastmail': 'fastmail.com',
  'tuta / tutanota': 'tuta.com',
  'zoho mail': 'zoho.com',

  // --- Social ---
  'x premium': 'x.com',
  'linkedin premium': 'linkedin.com',
  'reddit premium': 'reddit.com',
  'snapchat+': 'snapchat.com',
  'meta verified': 'meta.com',
  'instagram': 'instagram.com',
  'pinterest': 'pinterest.com',
  'quora+': 'quora.com',

  // --- Dating ---
  'tinder plus/gold/platinum': 'tinder.com',
  'bumble premium': 'bumble.com',
  'hinge preferred': 'hinge.co',
  'match.com': 'match.com',
  'okcupid': 'okcupid.com',
  'grindr': 'grindr.com',
  'feeld': 'feeld.co',
  'coffee meets bagel': 'coffeemeetsbagel.com',

  // --- Gaming ---
  'xbox game pass ultimate': 'xbox.com',
  'xbox game pass pc': 'xbox.com',
  'playstation plus essential': 'playstation.com',
  'playstation plus extra': 'playstation.com',
  'playstation plus premium': 'playstation.com',
  'nintendo switch online': 'nintendo.com',
  'ea play': 'ea.com',
  'ubisoft+': 'ubisoft.com',
  'humble choice': 'humblebundle.com',
  'geforce now': 'nvidia.com',
  'apple arcade': 'apple.com',
  'google play pass': 'play.google.com',
  'amazon luna': 'luna.amazon.com',
  'shadow pc': 'shadow.tech',
  'boosteroid': 'boosteroid.com',
  'blacknut': 'blacknut.com',
  'world of warcraft': 'worldofwarcraft.com',
  'final fantasy xiv': 'finalfantasyxiv.com',
  'eso plus': 'elderscrollsonline.com',
  'runescape': 'runescape.com',
  'eve online omega': 'eveonline.com',
  'fortnite crew': 'fortnite.com',
  'dota plus': 'dota2.com',
  'roblox premium': 'roblox.com',
  'minecraft realms': 'minecraft.net',

  // --- Education ---
  'coursera plus': 'coursera.org',
  'udemy': 'udemy.com',
  'edx': 'edx.org',
  'linkedin learning': 'learning.linkedin.com',
  'skillshare': 'skillshare.com',
  'masterclass': 'masterclass.com',
  'pluralsight': 'pluralsight.com',
  'datacamp': 'datacamp.com',
  'codecademy pro': 'codecademy.com',
  "o'reilly": 'oreilly.com',
  'frontend masters': 'frontendmasters.com',
  'brilliant': 'brilliant.org',
  'duolingo super': 'duolingo.com',
  'duolingo max': 'duolingo.com',
  'babbel': 'babbel.com',
  'rosetta stone': 'rosettastone.com',
  'busuu': 'busuu.com',
  'pimsleur': 'pimsleur.com',
  'italki': 'italki.com',
  'preply': 'preply.com',
  'memrise': 'memrise.com',
  'elsa speak': 'elsaspeak.com',
  'abcmouse': 'abcmouse.com',
  'ixl': 'ixl.com',
  'khan academy': 'khanacademy.org',
  'yousician': 'yousician.com',
  'simply piano': 'joytunes.com',
  'flowkey': 'flowkey.com',
  'overleaf': 'overleaf.com',
  'jstor': 'jstor.org',

  // --- Reading ---
  'medium': 'medium.com',
  'substack': 'substack.com',
  'the new york times': 'nytimes.com',
  'wall street journal': 'wsj.com',
  'washington post': 'washingtonpost.com',
  'financial times': 'ft.com',
  'bloomberg': 'bloomberg.com',
  'the economist': 'economist.com',
  'the atlantic': 'theatlantic.com',
  'the new yorker': 'newyorker.com',
  'wired': 'wired.com',
  'the information': 'theinformation.com',
  'stratechery': 'stratechery.com',
  "lenny's newsletter": 'lennysnewsletter.com',
  'the times (uk)': 'thetimes.co.uk',
  'the guardian': 'theguardian.com',
  'kindle unlimited': 'amazon.com',
  'apple news+': 'apple.com',
  'readly': 'readly.com',
  'magzter gold': 'magzter.com',
  'pressreader': 'pressreader.com',
  'readwise': 'readwise.io',
  'pocket premium': 'getpocket.com',
  'instapaper': 'instapaper.com',
  'feedly pro': 'feedly.com',
  'inoreader': 'inoreader.com',

  // --- Fitness / Health ---
  'peloton app': 'onepeloton.com',
  'apple fitness+': 'apple.com',
  'strava premium': 'strava.com',
  'fitbit premium': 'fitbit.com',
  'whoop': 'whoop.com',
  'oura ring': 'ouraring.com',
  'freeletics': 'freeletics.com',
  'classpass': 'classpass.com',
  'gympass / wellhub': 'wellhub.com',
  'les mills+': 'lesmills.com',
  'centr': 'centr.com',
  'alo moves': 'alomoves.com',
  'nike training club': 'nike.com',
  'myfitnesspal premium': 'myfitnesspal.com',
  'alltrails pro': 'alltrails.com',
  'calm': 'calm.com',
  'headspace': 'headspace.com',
  'waking up': 'wakingup.com',
  'ten percent happier': 'tenpercent.com',
  'betterhelp': 'betterhelp.com',
  'talkspace': 'talkspace.com',
  'noom': 'noom.com',
  'ww (weightwatchers)': 'weightwatchers.com',
  'flo premium': 'flo.health',
  'clue plus': 'helloclue.com',
  'natural cycles': 'naturalcycles.com',
  'hims': 'forhims.com',
  'hers': 'forhers.com',
  'ro': 'ro.co',
  'teladoc': 'teladoc.com',
  'one medical': 'onemedical.com',
  'lifesum': 'lifesum.com',

  // --- Shopping ---
  'amazon prime': 'amazon.com',
  'walmart+': 'walmart.com',
  'target circle 360': 'target.com',
  'costco': 'costco.com',
  "sam's club": 'samsclub.com',
  'doordash dashpass': 'doordash.com',
  'uber one': 'uber.com',
  'grubhub+': 'grubhub.com',
  'deliveroo plus': 'deliveroo.co.uk',
  'instacart+': 'instacart.com',
  'thrive market': 'thrivemarket.com',
  'hellofresh': 'hellofresh.com',
  'blue apron': 'blueapron.com',
  'home chef': 'homechef.com',
  'factor': 'factor75.com',
  'daily harvest': 'dailyharvest.com',
  'dollar shave club': 'dollarshaveclub.com',
  "harry's": 'harrys.com',
  'birchbox': 'birchbox.com',
  'ipsy': 'ipsy.com',
  'boxycharm': 'boxycharm.com',
  'rent the runway': 'renttherunway.com',
  'stitch fix': 'stitchfix.com',
  'fabfitfun': 'fabfitfun.com',
  'barkbox': 'barkbox.com',
  "farmer's dog": 'thefarmersdog.com',
  'rappi prime': 'rappi.com',
  'foodpanda pro': 'foodpanda.com',

  // --- Finance ---
  'tradingview': 'tradingview.com',
  'morningstar premium': 'morningstar.com',
  'seeking alpha': 'seekingalpha.com',
  'motley fool': 'fool.com',
  'ynab': 'ynab.com',
  'monarch money': 'monarchmoney.com',
  'quicken': 'quicken.com',
  'copilot money': 'copilot.money',
  'robinhood gold': 'robinhood.com',
  'coinbase one': 'coinbase.com',
  'coingecko premium': 'coingecko.com',
  'revolut premium': 'revolut.com',
  'n26': 'n26.com',
  'monzo plus': 'monzo.com',
  'wise premium': 'wise.com',
  'crunchbase pro': 'crunchbase.com',
  'pitchbook': 'pitchbook.com',
  'statista': 'statista.com',

  // --- Creator ---
  'patreon': 'patreon.com',
  'ko-fi': 'ko-fi.com',
  'buy me a coffee': 'buymeacoffee.com',
  'onlyfans': 'onlyfans.com',
  'fansly': 'fansly.com',
  'gumroad': 'gumroad.com',
  'bandcamp': 'bandcamp.com',
  'distrokid': 'distrokid.com',
  'memberful': 'memberful.com',
  'ghost pro': 'ghost.org',
  'squarespace': 'squarespace.com',
  'wix': 'wix.com',
  'webflow': 'webflow.com',
  'shopify': 'shopify.com',
  'teachable': 'teachable.com',
  'mailchimp': 'mailchimp.com',
  'beehiiv': 'beehiiv.com',
  'convertkit': 'convertkit.com',

  // --- Weather ---
  'windy premium': 'windy.com',
  'accuweather premium': 'accuweather.com',
  'carrot weather': 'meetcarrot.com',
  'radarscope': 'radarscope.com',
  'gaia gps pro': 'gaiagps.com',
  'onx maps': 'onxmaps.com',

  // --- China ---
  '爱奇艺 iqiyi': 'iqiyi.com',
  '优酷 youku': 'youku.com',
  '腾讯视频': 'v.qq.com',
  '芒果tv': 'mgtv.com',
  'bilibili 大会员': 'bilibili.com',
  '搜狐视频': 'tv.sohu.com',
  '咪咕视频': 'migu.cn',
  '西瓜视频': 'ixigua.com',
  'qq音乐': 'y.qq.com',
  '网易云音乐': 'music.163.com',
  '酷狗音乐': 'kugou.com',
  '酷我音乐': 'kuwo.cn',
  '咪咕音乐': 'migu.cn',
  '全民k歌': 'kg.qq.com',
  '知乎盐选': 'zhihu.com',
  '得到': 'dedao.cn',
  '喜马拉雅': 'ximalaya.com',
  '蜻蜓fm': 'qingting.fm',
  '荔枝fm': 'lizhi.fm',
  '微信读书': 'weread.qq.com',
  '掌阅 ireader': 'ireader.com.cn',
  '起点读书': 'qidian.com',
  '番茄小说': 'fanqienovel.com',
  '七猫小说': 'qimao.com',
  '京东读书': 'jd.com',
  '樊登读书': 'dushu.io',
  '淘宝 88vip': 'taobao.com',
  '京东 plus': 'jd.com',
  '拼多多省钱月卡': 'pinduoduo.com',
  '苏宁 super': 'suning.com',
  '唯品会超级vip': 'vip.com',
  '美团神会员': 'meituan.com',
  '饿了么超级会员': 'ele.me',
  '盒马x会员': 'freshhema.com',
  '叮咚买菜绿卡': 'ddxq.mobi',
  '瑞幸月卡': 'luckincoffee.com',
  '滴滴橙长会员': 'didiglobal.com',
  '哈啰骑行卡': 'hellobike.com',
  '美团单车月卡': 'meituan.com',
  '携程超级会员': 'ctrip.com',
  '飞猪': 'fliggy.com',
  '百度网盘超级会员': 'pan.baidu.com',
  '夸克网盘': 'quark.cn',
  '阿里云盘': 'alipan.com',
  '腾讯微云': 'weiyun.com',
  '迅雷超级会员': 'xunlei.com',
  'wps 会员': 'wps.cn',
  '有道云笔记': 'youdao.com',
  '石墨文档': 'shimo.im',
  '语雀': 'yuque.com',
  'flomo pro': 'flomoapp.com',
  '坚果云': 'jianguoyun.com',
  '微博 vip/svip': 'weibo.com',
  'qq超级会员': 'qq.com',
  '陌陌vip': 'immomo.com',
  '探探vip': 'tantanapp.com',
  'soul vip': 'soulapp.cn',
  '脉脉会员': 'maimai.cn',
  '原神月卡/纪行': 'ys.mihoyo.com',
  '崩坏星穹铁道': 'hsr.hoyoverse.com',
  '王者荣耀战令': 'pvp.qq.com',
  '和平精英精英手册': 'gamehelper.gm825.com',
  '腾讯心悦会员': 'xinyue.qq.com',
  '文心一言': 'yiyan.baidu.com',
  '通义千问': 'tongyi.aliyun.com',
  '讯飞星火': 'xinghuo.xfyun.cn',
  '豆包': 'doubao.com',
  'kimi': 'kimi.moonshot.cn',
  '智谱清言': 'chatglm.cn',
  '腾讯元宝': 'yuanbao.tencent.com',
  '同花顺': '10jqka.com.cn',
  '东方财富': 'eastmoney.com',
  '雪球': 'xueqiu.com',
  'keep 会员': 'keep.com',
  '薄荷健康': 'boohee.com',
  '丁香医生': 'dxy.com',
  '春雨医生': 'chunyuyisheng.com',
  '极客时间': 'time.geekbang.org',
  '掘金小册': 'juejin.cn',
  'csdn 会员': 'csdn.net',
  '慕课网': 'imooc.com',
  '中国大学mooc': 'icourse163.org',
  '知识星球': 'zsxq.com',
  '小鹅通': 'xiaoe-tech.com',
  '千聊': 'qlchat.com',
  '飞书 (lark)': 'feishu.cn',
  '钉钉 (dingtalk)': 'dingtalk.com',
  '企业微信': 'work.weixin.qq.com',
  '虎牙': 'huya.com',
  '斗鱼': 'douyu.com',
  '视觉中国': 'vcg.com',
  '小红书': 'xiaohongshu.com',
  '抖音': 'douyin.com',
  '快手': 'kuaishou.com',

  // --- Japan ---
  'u-next': 'unext.jp',
  'hulu japan': 'hulu.jp',
  'lemino': 'lemino.docomo.ne.jp',
  'abema': 'abema.tv',
  'fod': 'fod.fujitv.co.jp',
  'telasa': 'telasa.jp',
  'wowow': 'wowow.co.jp',
  'dmm tv': 'dmm.com',
  'd anime store': 'anime.dmkt-sp.jp',
  'nhk オンデマンド': 'nhk-ondemand.jp',
  'tver': 'tver.jp',
  'dazn japan': 'dazn.com',
  'line music': 'music.line.me',
  'awa': 'awa.fm',
  'rakuten music': 'music.rakuten.co.jp',
  'dヒッツ': 'dhits.docomo.ne.jp',
  'kindle unlimited jp': 'amazon.co.jp',
  'dマガジン': 'magazine.dmkt-sp.jp',
  '楽天マガジン': 'magazine.rakuten.co.jp',
  'コミックシーモア': 'cmoa.jp',
  'まんが王国': 'comic.k-manga.jp',
  'booklive': 'booklive.jp',
  'ピッコマ piccoma': 'piccoma.com',
  'lineマンガ': 'manga.line.me',
  'ジャンプ+': 'shonenjumpplus.com',
  'マガポケ': 'pocket.shonenmagazine.com',
  'book walker': 'bookwalker.jp',
  'amazon prime japan': 'amazon.co.jp',
  '楽天プレミアム': 'rakuten.co.jp',
  'yahoo! プレミアム': 'premium.yahoo.co.jp',
  '食べログ premium': 'tabelog.com',
  'cookpad premium': 'cookpad.com',
  'pixiv fanbox': 'fanbox.cc',
  'fantia': 'fantia.jp',
  'ci-en': 'ci-en.jp',
  'showroom': 'showroom-live.com',
  'pococha': 'www.pococha.com',
  '17live': '17.live',
  'note': 'note.com',
  'voicy': 'voicy.jp',
  'niconico': 'nicovideo.jp',
  '日経電子版': 'nikkei.com',
  'fate/grand order': 'fate-go.jp',
  'uma musume': 'umamusume.jp',

  // --- Korea ---
  'wavve': 'wavve.com',
  'tving': 'tving.com',
  'watcha': 'watcha.com',
  'coupang play': 'coupangplay.com',
  'laftel': 'laftel.net',
  'chzzk': 'chzzk.naver.com',
  'melon': 'melon.com',
  'genie music': 'genie.co.kr',
  'bugs': 'bugs.co.kr',
  'flo': 'music-flo.com',
  'vibe': 'vibe.naver.com',
  'naver webtoon': 'comic.naver.com',
  'kakao page': 'page.kakao.com',
  'lezhin comics': 'lezhin.com',
  'toomics': 'toomics.com',
  'ridi': 'ridibooks.com',
  '밀리의 서재 millie': 'millie.co.kr',
  'coupang rocket wow': 'coupang.com',
  'naver plus membership': 'naver.com',
  'market kurly': 'kurly.com',
  '배달의민족 baemin': 'baemin.com',
  '요기요 yogiyo': 'yogiyo.co.kr',
  'toss': 'toss.im',
  'kakao pay': 'kakaopay.com',
  'weverse': 'weverse.io',
  'bubble / dear u': 'dearu.co',
  'afreecatv': 'afreecatv.com',
  'spoon': 'spooncast.net',
  'pairs': 'pairs.lv',
  'omiai': 'omiai-jp.com',

  // --- India ---
  'jiocinema': 'jiocinema.com',
  'netflix india': 'netflix.com',
  'disney+ hotstar': 'hotstar.com',
  'zee5': 'zee5.com',
  'sonyliv': 'sonyliv.com',
  'altbalaji': 'altbalaji.com',
  'aha': 'aha.video',
  'sun nxt': 'sunnxt.com',
  'hoichoi': 'hoichoi.tv',
  'shemaroome': 'shemaroome.com',
  'airtel xstream': 'airtel.in',
  'amazon prime india': 'amazon.in',
  'flipkart plus': 'flipkart.com',
  'myntra insider': 'myntra.com',
  'tata neu': 'tataneu.com',
  'bigbasket': 'bigbasket.com',
  'blinkit': 'blinkit.com',
  'zepto': 'zeptonow.com',
  'swiggy one': 'swiggy.com',
  'zomato gold': 'zomato.com',
  "byju's": 'byjus.com',
  'unacademy': 'unacademy.com',
  'vedantu': 'vedantu.com',
  'physicswallah': 'pw.live',
  'upgrad': 'upgrad.com',
  'simplilearn': 'simplilearn.com',
  'scaler': 'scaler.com',
  'zerodha': 'zerodha.com',
  'groww': 'groww.in',
  'upstox': 'upstox.com',
  'et prime': 'economictimes.indiatimes.com',
  'moneycontrol pro': 'moneycontrol.com',
  'practo': 'practo.com',
  '1mg': '1mg.com',
  'pharmeasy': 'pharmeasy.in',
  'cult.fit': 'cult.fit',
  'healthifyme': 'healthifyme.com',
  'the ken': 'the-ken.com',
  'jiosaavn pro': 'jiosaavn.com',

  // --- SoutheastAsia ---
  'wetv': 'wetv.vip',
  'vidio': 'vidio.com',
  'mewatch': 'mewatch.sg',
  'astro': 'astro.com.my',
  'trueid': 'trueid.net',
  'vieon': 'vieon.vn',
  'iwanttfc': 'iwanttfc.com',
  'vivamax': 'vivamax.net',
  'catchplay+': 'catchplay.com',
  'kktv': 'kktv.me',
  'myvideo': 'myvideo.net.tw',
  'mytv super': 'mytvsuper.com',
  'grab': 'grab.com',
  'gojek': 'gojek.com',
  'goto': 'gotocompany.com',
  'shopee': 'shopee.com',
  'lazada': 'lazada.com',
  'tokopedia': 'tokopedia.com',
  'grabpay': 'grab.com',
  'gopay': 'gojek.com',
  'ovo': 'ovo.id',
  'dana': 'dana.id',
  'shopeepay': 'shopee.com',
  "touch'n go": 'tngdigital.com.my',
  'gcash': 'gcash.com',
  'maya': 'maya.ph',
  'momo': 'momo.vn',
  'zalopay': 'zalopay.vn',
  'truemoney': 'truemoney.com',
  'grabfood': 'grab.com',
  'gofood': 'gojek.com',
  'shopeefood': 'shopee.com',
  'line man': 'lineman.line.me',
  'deliveroo singapore': 'deliveroo.com.sg',
  'straits times': 'straitstimes.com',

  // --- Latin America ---
  'globoplay': 'globoplay.globo.com',
  'vix': 'vix.com',
  'claro video': 'clarovideo.com',
  'blim tv': 'blim.com',
  'flow': 'flow.com.ar',
  'rappi': 'rappi.com',
  'ifood': 'ifood.com.br',
  'mercado libre': 'mercadolibre.com',
  'nubank': 'nubank.com.br',
  'picpay': 'picpay.com',

  // --- Middle East ---
  'shahid vip': 'shahid.mbc.net',
  'osn+': 'osnplus.com',
  'tod': 'tod.tv',
  'starzplay arabia': 'starzplay.com',
  'careem': 'careem.com',

  // --- Africa ---
  'showmax': 'showmax.com',
  'dstv': 'dstv.com',
  'canal+ afrique': 'canalplus.com',
  'startimes': 'startimes.com.cn',
  'irokotv': 'irokotv.com',
  'm-pesa': 'safaricom.co.ke',

  // --- Russia ---
  'kinopoisk': 'kinopoisk.ru',
  'ivi': 'ivi.ru',
  'okko': 'okko.tv',
  'start': 'start.ru',
  'premier': 'premier.one',
  'yandex music': 'music.yandex.ru',
  'vk music': 'music.vk.com',
  'ozon premium': 'ozon.ru',
  'wildberries': 'wildberries.ru',
  'allegro smart': 'allegro.pl',
}

// Aliases for Simple Icons lookup
const ALIASES: Record<string, string> = {
  'chatgpt': 'openai',
  'chatgpt plus': 'openai',
  'chatgpt pro': 'openai',
  'claude pro': 'claude',
  'claude max': 'claude',
  'claude code': 'claude',
  'youtube premium': 'youtube',
  'youtube music': 'youtubemusic',
  'apple music': 'applemusic',
  'apple tv+': 'appletv',
  'ms 365': 'microsoftoffice',
  'microsoft 365': 'microsoftoffice',
  'github copilot': 'githubcopilot',
  'x premium': 'x',
  'discord nitro': 'discord',
  'telegram premium': 'telegram',
  'snapchat+': 'snapchat',
  'reddit premium': 'reddit',
  'linkedin premium': 'linkedin',
  'strava premium': 'strava',
}

export interface BrandIcon {
  title: string
  /** Simple Icons SVG string (filled if available) */
  svg: string | null
  /** Hex color (without #) */
  hex: string
  /** Favicon URL (filled if we have a domain) */
  faviconUrl: string | null
  /** Letter for last-resort fallback */
  letter: string
}

function deriveDomain(name: string, slug: string): string | null {
  const lower = name.toLowerCase().trim()
  if (DOMAIN_MAP[lower]) return DOMAIN_MAP[lower]
  // Best-guess: <slug>.com if slug looks like pure ASCII
  if (/^[a-z][a-z0-9]+$/.test(slug)) return `${slug}.com`
  return null
}

export function findBrandIcon(name: string, slug?: string): BrandIcon {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const simpleIcons = require('simple-icons')
  const normalized = name.toLowerCase().trim()
  const effectiveSlug = (slug ?? name).toLowerCase().replace(/[\s\-_.+]/g, '')
  const letter = name.charAt(0).toUpperCase()

  // 1. Simple Icons (alias first)
  const aliasSlug = ALIASES[normalized]
  if (aliasSlug) {
    const key = `si${aliasSlug.charAt(0).toUpperCase()}${aliasSlug.slice(1)}`
    const icon = simpleIcons[key]
    if (icon) {
      return {
        title: icon.title,
        svg: icon.svg,
        hex: icon.hex,
        faviconUrl: null,
        letter,
      }
    }
  }

  // 2. Simple Icons direct slug match
  const directKey = `si${effectiveSlug.charAt(0).toUpperCase()}${effectiveSlug.slice(1)}`
  const directIcon = simpleIcons[directKey]
  if (directIcon) {
    return {
      title: directIcon.title,
      svg: directIcon.svg,
      hex: directIcon.hex,
      faviconUrl: null,
      letter,
    }
  }

  // 3. Favicon via Google
  const domain = deriveDomain(name, slug ?? '')
  if (domain) {
    return {
      title: name,
      svg: null,
      hex: '6B7280',
      faviconUrl: `https://www.google.com/s2/favicons?domain=${domain}&sz=64`,
      letter,
    }
  }

  // 4. Letter fallback
  return {
    title: name,
    svg: null,
    hex: '6B7280',
    faviconUrl: null,
    letter,
  }
}
