/** Curated list of ~360 mainstream subscription services */
export interface ServiceTemplate {
  name: string
  slug: string
  category: string
  defaultPrice?: number
  defaultCurrency?: string
}

export const POPULAR_SERVICES: ServiceTemplate[] = [
  // --- Streaming (25) ---
  { name: 'Netflix', slug: 'netflix', category: 'Streaming', defaultPrice: 1599, defaultCurrency: 'USD' },
  { name: 'Disney+', slug: 'disneyplus', category: 'Streaming', defaultPrice: 1399, defaultCurrency: 'USD' },
  { name: 'YouTube Premium', slug: 'youtube', category: 'Streaming', defaultPrice: 1399, defaultCurrency: 'USD' },
  { name: 'Max (HBO)', slug: 'hbo', category: 'Streaming', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Prime Video', slug: 'amazonprimevideo', category: 'Streaming', defaultPrice: 899, defaultCurrency: 'USD' },
  { name: 'Apple TV+', slug: 'appletv', category: 'Streaming', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'Hulu', slug: 'hulu', category: 'Streaming', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Peacock', slug: 'peacock', category: 'Streaming', defaultPrice: 799, defaultCurrency: 'USD' },
  { name: 'Paramount+', slug: 'paramountplus', category: 'Streaming', defaultPrice: 799, defaultCurrency: 'USD' },
  { name: 'Crunchyroll', slug: 'crunchyroll', category: 'Streaming', defaultPrice: 799, defaultCurrency: 'USD' },
  { name: 'ESPN+', slug: 'espn', category: 'Streaming', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Starz', slug: 'starz', category: 'Streaming', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'YouTube TV', slug: 'youtubetv', category: 'Streaming', defaultPrice: 8299, defaultCurrency: 'USD' },
  { name: 'Sling TV', slug: 'slingtv', category: 'Streaming', defaultPrice: 4599, defaultCurrency: 'USD' },
  { name: 'fuboTV', slug: 'fubotv', category: 'Streaming', defaultPrice: 8499, defaultCurrency: 'USD' },
  { name: 'MUBI', slug: 'mubi', category: 'Streaming', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'Vimeo', slug: 'vimeo', category: 'Streaming', defaultPrice: 1200, defaultCurrency: 'USD' },
  { name: 'Sky', slug: 'sky', category: 'Streaming', defaultPrice: 1500, defaultCurrency: 'GBP' },
  { name: 'NOW', slug: 'nowtv', category: 'Streaming', defaultPrice: 699, defaultCurrency: 'GBP' },
  { name: 'Canal+', slug: 'canalplus', category: 'Streaming', defaultPrice: 1999, defaultCurrency: 'EUR' },
  { name: 'Viaplay', slug: 'viaplay', category: 'Streaming', defaultPrice: 16900, defaultCurrency: 'SEK' },
  { name: 'SkyShowtime', slug: 'skyshowtime', category: 'Streaming', defaultPrice: 699, defaultCurrency: 'EUR' },
  { name: 'Stan', slug: 'stan', category: 'Streaming', defaultPrice: 1200, defaultCurrency: 'AUD' },
  { name: 'Viu', slug: 'viu', category: 'Streaming', defaultPrice: 2900, defaultCurrency: 'HKD' },
  { name: 'Twitch Turbo', slug: 'twitch', category: 'Streaming', defaultPrice: 999, defaultCurrency: 'USD' },

  // --- Music (12) ---
  { name: 'Spotify', slug: 'spotify', category: 'Music', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Apple Music', slug: 'applemusic', category: 'Music', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'YouTube Music', slug: 'youtubemusic', category: 'Music', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Tidal', slug: 'tidal', category: 'Music', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Amazon Music', slug: 'amazonmusic', category: 'Music', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Deezer', slug: 'deezer', category: 'Music', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'SoundCloud Go+', slug: 'soundcloud', category: 'Music', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Pandora', slug: 'pandora', category: 'Music', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Qobuz', slug: 'qobuz', category: 'Music', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'SiriusXM', slug: 'siriusxm', category: 'Music', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Anghami', slug: 'anghami', category: 'Music', defaultPrice: 999, defaultCurrency: 'AED' },
  { name: 'Boomplay', slug: 'boomplay', category: 'Music', defaultPrice: 199, defaultCurrency: 'USD' },
  // --- Podcasts & Audiobooks (4) ---
  { name: 'Audible', slug: 'audible', category: 'Podcasts', defaultPrice: 1495, defaultCurrency: 'USD' },
  { name: 'Scribd/Everand', slug: 'scribd', category: 'Podcasts', defaultPrice: 1199, defaultCurrency: 'USD' },
  { name: 'Apple Podcasts', slug: 'applepodcasts', category: 'Podcasts', defaultPrice: 499, defaultCurrency: 'USD' },
  { name: 'Spotify Podcasts', slug: 'spotify', category: 'Podcasts', defaultPrice: 1099, defaultCurrency: 'USD' },
  // --- Sports (4) ---
  { name: 'DAZN', slug: 'dazn', category: 'Sports', defaultPrice: 2499, defaultCurrency: 'USD' },
  { name: 'The Athletic', slug: 'theathletic', category: 'Sports', defaultPrice: 799, defaultCurrency: 'USD' },
  { name: 'FanDuel', slug: 'fanduel', category: 'Sports' },
  { name: 'DraftKings', slug: 'draftkings', category: 'Sports' },

  // --- AI (15) ---
  { name: 'ChatGPT Plus', slug: 'openai', category: 'AI', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'ChatGPT Pro', slug: 'openai', category: 'AI', defaultPrice: 20000, defaultCurrency: 'USD' },
  { name: 'Claude Pro', slug: 'claude', category: 'AI', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'Gemini Advanced', slug: 'googlegemini', category: 'AI', defaultPrice: 1999, defaultCurrency: 'USD' },
  { name: 'Microsoft Copilot Pro', slug: 'microsoftcopilot', category: 'AI', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'Perplexity Pro', slug: 'perplexity', category: 'AI', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'Midjourney', slug: 'midjourney', category: 'AI', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'Runway ML', slug: 'runwayml', category: 'AI', defaultPrice: 1200, defaultCurrency: 'USD' },
  { name: 'ElevenLabs', slug: 'elevenlabs', category: 'AI', defaultPrice: 2200, defaultCurrency: 'USD' },
  { name: 'Suno AI', slug: 'suno', category: 'AI', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'Grammarly Premium', slug: 'grammarly', category: 'AI', defaultPrice: 1200, defaultCurrency: 'USD' },
  { name: 'DeepL Pro', slug: 'deepl', category: 'AI', defaultPrice: 1049, defaultCurrency: 'USD' },
  { name: 'Descript', slug: 'descript', category: 'AI', defaultPrice: 1200, defaultCurrency: 'USD' },
  { name: 'Jasper AI', slug: 'jasper', category: 'AI', defaultPrice: 3900, defaultCurrency: 'USD' },
  { name: 'Synthesia', slug: 'synthesia', category: 'AI', defaultPrice: 2900, defaultCurrency: 'USD' },
  // --- Developer (20) ---
  { name: 'GitHub Pro', slug: 'github', category: 'Developer', defaultPrice: 400, defaultCurrency: 'USD' },
  { name: 'GitHub Copilot', slug: 'githubcopilot', category: 'Developer', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'GitLab Premium', slug: 'gitlab', category: 'Developer', defaultPrice: 2900, defaultCurrency: 'USD' },
  { name: 'JetBrains All Products', slug: 'jetbrains', category: 'Developer', defaultPrice: 2490, defaultCurrency: 'USD' },
  { name: 'Cursor Pro', slug: 'cursor', category: 'Developer', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'Replit', slug: 'replit', category: 'Developer', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'Postman', slug: 'postman', category: 'Developer', defaultPrice: 1400, defaultCurrency: 'USD' },
  { name: 'Docker Pro', slug: 'docker', category: 'Developer', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'Vercel Pro', slug: 'vercel', category: 'Developer', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'Netlify Pro', slug: 'netlify', category: 'Developer', defaultPrice: 1900, defaultCurrency: 'USD' },
  { name: 'Railway', slug: 'railway', category: 'Developer', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'Render', slug: 'render', category: 'Developer', defaultPrice: 1900, defaultCurrency: 'USD' },
  { name: 'DigitalOcean', slug: 'digitalocean', category: 'Developer', defaultPrice: 400, defaultCurrency: 'USD' },
  { name: 'Supabase', slug: 'supabase', category: 'Developer', defaultPrice: 2500, defaultCurrency: 'USD' },
  { name: 'Cloudflare', slug: 'cloudflare', category: 'Developer', defaultPrice: 2500, defaultCurrency: 'USD' },
  { name: 'Sentry', slug: 'sentry', category: 'Developer', defaultPrice: 2600, defaultCurrency: 'USD' },
  { name: 'Datadog', slug: 'datadog', category: 'Developer', defaultPrice: 1500, defaultCurrency: 'USD' },
  { name: 'Tailscale', slug: 'tailscale', category: 'Developer', defaultPrice: 600, defaultCurrency: 'USD' },
  { name: 'LeetCode', slug: 'leetcode', category: 'Developer', defaultPrice: 3500, defaultCurrency: 'USD' },
  { name: 'HackerRank', slug: 'hackerrank', category: 'Developer', defaultPrice: 3500, defaultCurrency: 'USD' },
  // --- Productivity (20) ---
  { name: 'Microsoft 365', slug: 'microsoftoffice', category: 'Productivity', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Google Workspace', slug: 'google', category: 'Productivity', defaultPrice: 600, defaultCurrency: 'USD' },
  { name: 'Notion', slug: 'notion', category: 'Productivity', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'Obsidian Sync', slug: 'obsidian', category: 'Productivity', defaultPrice: 400, defaultCurrency: 'USD' },
  { name: 'Evernote', slug: 'evernote', category: 'Productivity', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'Airtable', slug: 'airtable', category: 'Productivity', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'Trello', slug: 'trello', category: 'Productivity', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'Asana', slug: 'asana', category: 'Productivity', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Monday.com', slug: 'mondaydotcom', category: 'Productivity', defaultPrice: 900, defaultCurrency: 'USD' },
  { name: 'Jira', slug: 'jira', category: 'Productivity', defaultPrice: 790, defaultCurrency: 'USD' },
  { name: 'Linear', slug: 'linear', category: 'Productivity', defaultPrice: 800, defaultCurrency: 'USD' },
  { name: 'ClickUp', slug: 'clickup', category: 'Productivity', defaultPrice: 700, defaultCurrency: 'USD' },
  { name: 'Todoist Pro', slug: 'todoist', category: 'Productivity', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'Raycast Pro', slug: 'raycast', category: 'Productivity', defaultPrice: 800, defaultCurrency: 'USD' },
  { name: 'Superhuman', slug: 'superhuman', category: 'Productivity', defaultPrice: 3000, defaultCurrency: 'USD' },
  { name: 'Calendly', slug: 'calendly', category: 'Productivity', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'Zapier', slug: 'zapier', category: 'Productivity', defaultPrice: 1999, defaultCurrency: 'USD' },
  { name: 'Make', slug: 'make', category: 'Productivity', defaultPrice: 900, defaultCurrency: 'USD' },
  { name: 'Miro', slug: 'miro', category: 'Productivity', defaultPrice: 800, defaultCurrency: 'USD' },
  { name: 'Loom', slug: 'loom', category: 'Productivity', defaultPrice: 1250, defaultCurrency: 'USD' },

  // --- Design (12) ---
  { name: 'Adobe Creative Cloud', slug: 'adobecreativecloud', category: 'Design', defaultPrice: 5999, defaultCurrency: 'USD' },
  { name: 'Adobe Photoshop', slug: 'adobephotoshop', category: 'Design', defaultPrice: 2299, defaultCurrency: 'USD' },
  { name: 'Adobe Lightroom', slug: 'adobelightroom', category: 'Design', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Adobe Premiere Pro', slug: 'adobepremierepro', category: 'Design', defaultPrice: 2299, defaultCurrency: 'USD' },
  { name: 'Figma', slug: 'figma', category: 'Design', defaultPrice: 1500, defaultCurrency: 'USD' },
  { name: 'Canva Pro', slug: 'canva', category: 'Design', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'Sketch', slug: 'sketch', category: 'Design', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'Framer', slug: 'framer', category: 'Design', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'CapCut Pro', slug: 'capcut', category: 'Design', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'DaVinci Resolve Studio', slug: 'davinciresolve', category: 'Design' },
  { name: 'Shutterstock', slug: 'shutterstock', category: 'Design', defaultPrice: 4900, defaultCurrency: 'USD' },
  { name: 'Envato Elements', slug: 'envato', category: 'Design', defaultPrice: 1650, defaultCurrency: 'USD' },

  // --- Cloud (6) ---
  { name: 'iCloud+', slug: 'icloud', category: 'Cloud', defaultPrice: 99, defaultCurrency: 'USD' },
  { name: 'Google One', slug: 'google', category: 'Cloud', defaultPrice: 199, defaultCurrency: 'USD' },
  { name: 'Dropbox Plus', slug: 'dropbox', category: 'Cloud', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'OneDrive', slug: 'microsoftonedrive', category: 'Cloud', defaultPrice: 199, defaultCurrency: 'USD' },
  { name: 'MEGA', slug: 'mega', category: 'Cloud', defaultPrice: 535, defaultCurrency: 'USD' },
  { name: 'Backblaze', slug: 'backblaze', category: 'Cloud', defaultPrice: 900, defaultCurrency: 'USD' },

  // --- VPN (5) ---
  { name: 'NordVPN', slug: 'nordvpn', category: 'VPN', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'ExpressVPN', slug: 'expressvpn', category: 'VPN', defaultPrice: 1295, defaultCurrency: 'USD' },
  { name: 'Surfshark', slug: 'surfshark', category: 'VPN', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'ProtonVPN', slug: 'protonvpn', category: 'VPN', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Mullvad VPN', slug: 'mullvad', category: 'VPN', defaultPrice: 546, defaultCurrency: 'USD' },

  // --- Security (5) ---
  { name: '1Password', slug: '1password', category: 'Security', defaultPrice: 299, defaultCurrency: 'USD' },
  { name: 'Bitwarden Premium', slug: 'bitwarden', category: 'Security', defaultPrice: 83, defaultCurrency: 'USD' },
  { name: 'Dashlane', slug: 'dashlane', category: 'Security', defaultPrice: 499, defaultCurrency: 'USD' },
  { name: 'LastPass Premium', slug: 'lastpass', category: 'Security', defaultPrice: 300, defaultCurrency: 'USD' },
  { name: 'Proton Unlimited', slug: 'proton', category: 'Security', defaultPrice: 999, defaultCurrency: 'USD' },

  // --- Communication (6) ---
  { name: 'Slack Pro', slug: 'slack', category: 'Communication', defaultPrice: 875, defaultCurrency: 'USD' },
  { name: 'Zoom', slug: 'zoom', category: 'Communication', defaultPrice: 1333, defaultCurrency: 'USD' },
  { name: 'Microsoft Teams', slug: 'microsoftteams', category: 'Communication', defaultPrice: 400, defaultCurrency: 'USD' },
  { name: 'Discord Nitro', slug: 'discord', category: 'Communication', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Telegram Premium', slug: 'telegram', category: 'Communication', defaultPrice: 499, defaultCurrency: 'USD' },
  { name: 'WhatsApp', slug: 'whatsapp', category: 'Communication' },

  // --- Email (4) ---
  { name: 'Proton Mail Plus', slug: 'protonmail', category: 'Email', defaultPrice: 399, defaultCurrency: 'USD' },
  { name: 'HEY', slug: 'hey', category: 'Email', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Fastmail', slug: 'fastmail', category: 'Email', defaultPrice: 300, defaultCurrency: 'USD' },
  { name: 'Tuta', slug: 'tutanota', category: 'Email', defaultPrice: 960, defaultCurrency: 'EUR' },
  // --- Social (6) ---
  { name: 'X Premium', slug: 'x', category: 'Social', defaultPrice: 800, defaultCurrency: 'USD' },
  { name: 'LinkedIn Premium', slug: 'linkedin', category: 'Social', defaultPrice: 2999, defaultCurrency: 'USD' },
  { name: 'Reddit Premium', slug: 'reddit', category: 'Social', defaultPrice: 599, defaultCurrency: 'USD' },
  { name: 'Snapchat+', slug: 'snapchat', category: 'Social', defaultPrice: 399, defaultCurrency: 'USD' },
  { name: 'Meta Verified', slug: 'meta', category: 'Social', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'Quora+', slug: 'quora', category: 'Social', defaultPrice: 500, defaultCurrency: 'USD' },
  // --- Dating (5) ---
  { name: 'Tinder Plus/Gold/Platinum', slug: 'tinder', category: 'Dating', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Bumble Premium', slug: 'bumble', category: 'Dating', defaultPrice: 1699, defaultCurrency: 'USD' },
  { name: 'Hinge Preferred', slug: 'hinge', category: 'Dating', defaultPrice: 2999, defaultCurrency: 'USD' },
  { name: 'Match.com', slug: 'matchdotcom', category: 'Dating', defaultPrice: 4599, defaultCurrency: 'USD' },
  { name: 'Grindr', slug: 'grindr', category: 'Dating', defaultPrice: 1999, defaultCurrency: 'USD' },
  // --- Gaming (15) ---
  { name: 'Xbox Game Pass Ultimate', slug: 'xbox', category: 'Gaming', defaultPrice: 2999, defaultCurrency: 'USD' },
  { name: 'Xbox Game Pass PC', slug: 'xbox', category: 'Gaming', defaultPrice: 1649, defaultCurrency: 'USD' },
  { name: 'PlayStation Plus Essential', slug: 'playstation', category: 'Gaming', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'PlayStation Plus Extra', slug: 'playstation', category: 'Gaming', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'PlayStation Plus Premium', slug: 'playstation', category: 'Gaming', defaultPrice: 1799, defaultCurrency: 'USD' },
  { name: 'Nintendo Switch Online', slug: 'nintendoswitch', category: 'Gaming', defaultPrice: 399, defaultCurrency: 'USD' },
  { name: 'EA Play', slug: 'ea', category: 'Gaming', defaultPrice: 599, defaultCurrency: 'USD' },
  { name: 'Ubisoft+', slug: 'ubisoft', category: 'Gaming', defaultPrice: 1799, defaultCurrency: 'USD' },
  { name: 'GeForce NOW', slug: 'nvidia', category: 'Gaming', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Apple Arcade', slug: 'apple', category: 'Gaming', defaultPrice: 699, defaultCurrency: 'USD' },
  { name: 'Google Play Pass', slug: 'googleplay', category: 'Gaming', defaultPrice: 499, defaultCurrency: 'USD' },
  { name: 'World of Warcraft', slug: 'worldofwarcraft', category: 'Gaming', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'Final Fantasy XIV', slug: 'finalfantasy', category: 'Gaming', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'Fortnite Crew', slug: 'fortnite', category: 'Gaming', defaultPrice: 1199, defaultCurrency: 'USD' },
  { name: 'Roblox Premium', slug: 'roblox', category: 'Gaming', defaultPrice: 499, defaultCurrency: 'USD' },
  // --- Education (18) ---
  { name: 'Coursera Plus', slug: 'coursera', category: 'Education', defaultPrice: 5900, defaultCurrency: 'USD' },
  { name: 'Udemy', slug: 'udemy', category: 'Education', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'edX', slug: 'edx', category: 'Education', defaultPrice: 5000, defaultCurrency: 'USD' },
  { name: 'LinkedIn Learning', slug: 'linkedin', category: 'Education', defaultPrice: 2999, defaultCurrency: 'USD' },
  { name: 'Skillshare', slug: 'skillshare', category: 'Education', defaultPrice: 1400, defaultCurrency: 'USD' },
  { name: 'MasterClass', slug: 'masterclass', category: 'Education', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'Pluralsight', slug: 'pluralsight', category: 'Education', defaultPrice: 2900, defaultCurrency: 'USD' },
  { name: 'DataCamp', slug: 'datacamp', category: 'Education', defaultPrice: 1300, defaultCurrency: 'USD' },
  { name: 'Codecademy Pro', slug: 'codecademy', category: 'Education', defaultPrice: 2499, defaultCurrency: 'USD' },
  { name: "O'Reilly", slug: 'oreilly', category: 'Education' },
  { name: 'Brilliant', slug: 'brilliant', category: 'Education', defaultPrice: 1249, defaultCurrency: 'USD' },
  { name: 'Duolingo Super', slug: 'duolingo', category: 'Education', defaultPrice: 699, defaultCurrency: 'USD' },
  { name: 'Duolingo Max', slug: 'duolingo', category: 'Education', defaultPrice: 2999, defaultCurrency: 'USD' },
  { name: 'Babbel', slug: 'babbel', category: 'Education', defaultPrice: 1395, defaultCurrency: 'USD' },
  { name: 'Rosetta Stone', slug: 'rosettastone', category: 'Education', defaultPrice: 1199, defaultCurrency: 'USD' },
  { name: 'Khan Academy', slug: 'khanacademy', category: 'Education' },
  { name: 'Overleaf', slug: 'overleaf', category: 'Education', defaultPrice: 2100, defaultCurrency: 'USD' },
  { name: 'Frontend Masters', slug: 'frontendmasters', category: 'Education', defaultPrice: 3900, defaultCurrency: 'USD' },
  // --- Reading (18) ---
  { name: 'Medium', slug: 'medium', category: 'Reading', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'Substack', slug: 'substack', category: 'Reading' },
  { name: 'The New York Times', slug: 'newyorktimes', category: 'Reading', defaultPrice: 1700, defaultCurrency: 'USD' },
  { name: 'Wall Street Journal', slug: 'wsj', category: 'Reading', defaultPrice: 3899, defaultCurrency: 'USD' },
  { name: 'Washington Post', slug: 'thewashingtonpost', category: 'Reading', defaultPrice: 1200, defaultCurrency: 'USD' },
  { name: 'Financial Times', slug: 'financialtimes', category: 'Reading', defaultPrice: 4500, defaultCurrency: 'USD' },
  { name: 'Bloomberg', slug: 'bloomberg', category: 'Reading', defaultPrice: 3499, defaultCurrency: 'USD' },
  { name: 'The Economist', slug: 'economist', category: 'Reading', defaultPrice: 1400, defaultCurrency: 'USD' },
  { name: 'The Atlantic', slug: 'theatlantic', category: 'Reading', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'The New Yorker', slug: 'thenewyorker', category: 'Reading', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'Wired', slug: 'wired', category: 'Reading', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'The Information', slug: 'theinformation', category: 'Reading', defaultPrice: 4000, defaultCurrency: 'USD' },
  { name: 'The Guardian', slug: 'theguardian', category: 'Reading', defaultPrice: 1200, defaultCurrency: 'USD' },
  { name: 'Kindle Unlimited', slug: 'amazon', category: 'Reading', defaultPrice: 1199, defaultCurrency: 'USD' },
  { name: 'Apple News+', slug: 'apple', category: 'Reading', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'Readwise', slug: 'readwise', category: 'Reading', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Pocket Premium', slug: 'pocket', category: 'Reading', defaultPrice: 499, defaultCurrency: 'USD' },
  { name: 'Feedly Pro', slug: 'feedly', category: 'Reading', defaultPrice: 600, defaultCurrency: 'USD' },

  // --- Fitness (10) ---
  { name: 'Peloton App', slug: 'peloton', category: 'Fitness', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'Apple Fitness+', slug: 'apple', category: 'Fitness', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Strava Premium', slug: 'strava', category: 'Fitness', defaultPrice: 1199, defaultCurrency: 'USD' },
  { name: 'Fitbit Premium', slug: 'fitbit', category: 'Fitness', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'WHOOP', slug: 'whoop', category: 'Fitness', defaultPrice: 3000, defaultCurrency: 'USD' },
  { name: 'Oura Ring', slug: 'oura', category: 'Fitness', defaultPrice: 599, defaultCurrency: 'USD' },
  { name: 'ClassPass', slug: 'classpass', category: 'Fitness', defaultPrice: 7900, defaultCurrency: 'USD' },
  { name: 'Nike Training Club', slug: 'nike', category: 'Fitness' },
  { name: 'MyFitnessPal Premium', slug: 'myfitnesspal', category: 'Fitness', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'AllTrails Pro', slug: 'alltrails', category: 'Fitness', defaultPrice: 300, defaultCurrency: 'USD' },
  // --- Health (10) ---
  { name: 'Calm', slug: 'calm', category: 'Health', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'Headspace', slug: 'headspace', category: 'Health', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'BetterHelp', slug: 'betterhelp', category: 'Health', defaultPrice: 32000, defaultCurrency: 'USD' },
  { name: 'Talkspace', slug: 'talkspace', category: 'Health', defaultPrice: 27600, defaultCurrency: 'USD' },
  { name: 'Noom', slug: 'noom', category: 'Health', defaultPrice: 5900, defaultCurrency: 'USD' },
  { name: 'WW (WeightWatchers)', slug: 'weightwatchers', category: 'Health', defaultPrice: 2300, defaultCurrency: 'USD' },
  { name: 'Flo Premium', slug: 'flo', category: 'Health', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Hims', slug: 'hims', category: 'Health', defaultPrice: 2500, defaultCurrency: 'USD' },
  { name: 'Hers', slug: 'hers', category: 'Health', defaultPrice: 2500, defaultCurrency: 'USD' },
  { name: 'Teladoc', slug: 'teladoc', category: 'Health' },

  // --- Shopping (18) ---
  { name: 'Amazon Prime', slug: 'amazonprime', category: 'Shopping', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'Walmart+', slug: 'walmart', category: 'Shopping', defaultPrice: 1295, defaultCurrency: 'USD' },
  { name: 'Target Circle 360', slug: 'target', category: 'Shopping', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Costco', slug: 'costco', category: 'Shopping', defaultPrice: 542, defaultCurrency: 'USD' },
  { name: "Sam's Club", slug: 'samsclub', category: 'Shopping' },
  { name: 'DoorDash DashPass', slug: 'doordash', category: 'Shopping', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Uber One', slug: 'uber', category: 'Shopping', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Grubhub+', slug: 'grubhub', category: 'Shopping', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Deliveroo Plus', slug: 'deliveroo', category: 'Shopping', defaultPrice: 349, defaultCurrency: 'GBP' },
  { name: 'Instacart+', slug: 'instacart', category: 'Shopping', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'HelloFresh', slug: 'hellofresh', category: 'Shopping' },
  { name: 'Blue Apron', slug: 'blueapron', category: 'Shopping' },
  { name: 'Home Chef', slug: 'homechef', category: 'Shopping' },
  { name: 'Dollar Shave Club', slug: 'dollarshaveclub', category: 'Shopping', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: "Harry's", slug: 'harrys', category: 'Shopping' },
  { name: 'Rent the Runway', slug: 'renttherunway', category: 'Shopping', defaultPrice: 9400, defaultCurrency: 'USD' },
  { name: 'Stitch Fix', slug: 'stitchfix', category: 'Shopping' },
  { name: 'BarkBox', slug: 'barkbox', category: 'Shopping', defaultPrice: 2300, defaultCurrency: 'USD' },
  // --- Finance (12) ---
  { name: 'TradingView', slug: 'tradingview', category: 'Finance', defaultPrice: 1495, defaultCurrency: 'USD' },
  { name: 'Morningstar Premium', slug: 'morningstar', category: 'Finance', defaultPrice: 2499, defaultCurrency: 'USD' },
  { name: 'Seeking Alpha', slug: 'seekingalpha', category: 'Finance', defaultPrice: 2999, defaultCurrency: 'USD' },
  { name: 'Motley Fool', slug: 'motleyfool', category: 'Finance', defaultPrice: 1658, defaultCurrency: 'USD' },
  { name: 'YNAB', slug: 'ynab', category: 'Finance', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'Monarch Money', slug: 'monarchmoney', category: 'Finance', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'Robinhood Gold', slug: 'robinhood', category: 'Finance', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'Coinbase One', slug: 'coinbase', category: 'Finance', defaultPrice: 2999, defaultCurrency: 'USD' },
  { name: 'Revolut Premium', slug: 'revolut', category: 'Finance', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Wise Premium', slug: 'wise', category: 'Finance' },
  { name: 'N26', slug: 'n26', category: 'Finance', defaultPrice: 499, defaultCurrency: 'EUR' },
  { name: 'Monzo Plus', slug: 'monzo', category: 'Finance', defaultPrice: 700, defaultCurrency: 'GBP' },
  // --- Creator Economy (10) ---
  { name: 'Patreon', slug: 'patreon', category: 'Creator', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'Ko-fi', slug: 'kofi', category: 'Creator' },
  { name: 'Buy Me a Coffee', slug: 'buymeacoffee', category: 'Creator' },
  { name: 'OnlyFans', slug: 'onlyfans', category: 'Creator' },
  { name: 'Gumroad', slug: 'gumroad', category: 'Creator' },
  { name: 'Ghost Pro', slug: 'ghost', category: 'Creator', defaultPrice: 900, defaultCurrency: 'USD' },
  { name: 'Squarespace', slug: 'squarespace', category: 'Creator', defaultPrice: 1600, defaultCurrency: 'USD' },
  { name: 'Wix', slug: 'wix', category: 'Creator', defaultPrice: 1700, defaultCurrency: 'USD' },
  { name: 'Webflow', slug: 'webflow', category: 'Creator', defaultPrice: 1800, defaultCurrency: 'USD' },
  { name: 'Shopify', slug: 'shopify', category: 'Creator', defaultPrice: 2900, defaultCurrency: 'USD' },

  // --- Weather (3) ---
  { name: 'Windy Premium', slug: 'windy', category: 'Weather', defaultPrice: 167, defaultCurrency: 'USD' },
  { name: 'AccuWeather Premium', slug: 'accuweather', category: 'Weather', defaultPrice: 99, defaultCurrency: 'USD' },
  { name: 'Carrot Weather', slug: 'carrotweather', category: 'Weather', defaultPrice: 499, defaultCurrency: 'USD' },
  // ===============================================================
  // Regional — kept mainstream / most popular only
  // ===============================================================

  // --- China (50) — 主流服务 ---
  // 视频 (5)
  { name: '爱奇艺 iQIYI', slug: 'iqiyi', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '优酷 Youku', slug: 'youku', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '腾讯视频', slug: 'tencentvideo', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '芒果TV', slug: 'mangotv', category: 'China', defaultPrice: 1900, defaultCurrency: 'CNY' },
  { name: 'bilibili 大会员', slug: 'bilibili', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  // 音乐 (2)
  { name: 'QQ音乐', slug: 'qqmusic', category: 'China', defaultPrice: 1500, defaultCurrency: 'CNY' },
  { name: '网易云音乐', slug: 'neteasecloudmusic', category: 'China', defaultPrice: 1500, defaultCurrency: 'CNY' },
  // 阅读/知识 (4)
  { name: '微信读书', slug: 'weread', category: 'China', defaultPrice: 1900, defaultCurrency: 'CNY' },
  { name: '知乎盐选', slug: 'zhihu', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '得到', slug: 'dedao', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '喜马拉雅', slug: 'ximalaya', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  // 电商 (3)
  { name: '淘宝 88VIP', slug: 'taobao', category: 'China', defaultPrice: 7400, defaultCurrency: 'CNY' },
  { name: '京东 PLUS', slug: 'jd', category: 'China', defaultPrice: 1242, defaultCurrency: 'CNY' },
  { name: '拼多多省钱月卡', slug: 'pinduoduo', category: 'China', defaultPrice: 990, defaultCurrency: 'CNY' },
  // 外卖 (2)
  { name: '美团神会员', slug: 'meituan', category: 'China', defaultPrice: 1500, defaultCurrency: 'CNY' },
  { name: '饿了么超级会员', slug: 'eleme', category: 'China', defaultPrice: 1500, defaultCurrency: 'CNY' },
  // 出行/旅行 (2)
  { name: '滴滴橙长会员', slug: 'didi', category: 'China', defaultPrice: 1500, defaultCurrency: 'CNY' },
  { name: '携程超级会员', slug: 'ctrip', category: 'China', defaultPrice: 4900, defaultCurrency: 'CNY' },
  // 云存储 (2)
  { name: '百度网盘超级会员', slug: 'baidupan', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '阿里云盘', slug: 'aliyunpan', category: 'China', defaultPrice: 1300, defaultCurrency: 'CNY' },
  // 办公 (4)
  { name: 'WPS 会员', slug: 'wps', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '石墨文档', slug: 'shimo', category: 'China', defaultPrice: 3500, defaultCurrency: 'CNY' },
  { name: '语雀', slug: 'yuque', category: 'China', defaultPrice: 600, defaultCurrency: 'CNY' },
  { name: '飞书 (Lark)', slug: 'feishu', category: 'China' },
  // 社交/通讯 (3)
  { name: '钉钉 (DingTalk)', slug: 'dingtalk', category: 'China' },
  { name: '微博 VIP/SVIP', slug: 'sinaweibo', category: 'China', defaultPrice: 1200, defaultCurrency: 'CNY' },
  { name: 'QQ超级会员', slug: 'tencentqq', category: 'China', defaultPrice: 3000, defaultCurrency: 'CNY' },
  // 短视频/直播 (3)
  { name: '小红书', slug: 'xiaohongshu', category: 'China' },
  { name: '抖音', slug: 'douyin', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '快手', slug: 'kuaishou', category: 'China' },
  // 游戏 (3)
  { name: '原神', slug: 'genshin', category: 'China', defaultPrice: 3000, defaultCurrency: 'CNY' },
  { name: '王者荣耀战令', slug: 'wangzhe', category: 'China', defaultPrice: 9000, defaultCurrency: 'CNY' },
  { name: '和平精英精英手册', slug: 'pubgm', category: 'China', defaultPrice: 6000, defaultCurrency: 'CNY' },
  // AI (4)
  { name: '文心一言', slug: 'wenxin', category: 'China', defaultPrice: 4990, defaultCurrency: 'CNY' },
  { name: '通义千问', slug: 'tongyi', category: 'China', defaultPrice: 3000, defaultCurrency: 'CNY' },
  { name: '豆包', slug: 'doubao', category: 'China' },
  { name: 'Kimi', slug: 'kimi', category: 'China' },
  // 金融 (2)
  { name: '雪球', slug: 'xueqiu', category: 'China', defaultPrice: 2000, defaultCurrency: 'CNY' },
  { name: '东方财富', slug: 'eastmoney', category: 'China' },
  // 健康/健身 (1)
  { name: 'Keep 会员', slug: 'keep', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  // 教育 (2)
  { name: '极客时间', slug: 'geektime', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '掘金小册', slug: 'juejin', category: 'China' },

  // --- Japan (5) ---
  { name: 'Amazon Prime Japan', slug: 'amazon', category: 'Japan', defaultPrice: 60000, defaultCurrency: 'JPY' },
  { name: 'LINE Music', slug: 'linemusic', category: 'Japan', defaultPrice: 98000, defaultCurrency: 'JPY' },
  { name: 'ABEMA', slug: 'abema', category: 'Japan', defaultPrice: 1080, defaultCurrency: 'JPY' },
  { name: 'U-NEXT', slug: 'unext', category: 'Japan', defaultPrice: 218900, defaultCurrency: 'JPY' },
  { name: 'Niconico', slug: 'niconico', category: 'Japan', defaultPrice: 790, defaultCurrency: 'JPY' },
  // --- Korea (5) ---
  { name: 'Melon', slug: 'melon', category: 'Korea', defaultPrice: 10900, defaultCurrency: 'KRW' },
  { name: 'Coupang Rocket WOW', slug: 'coupang', category: 'Korea', defaultPrice: 499000, defaultCurrency: 'KRW' },
  { name: 'Toss', slug: 'toss', category: 'Korea', defaultPrice: 5900, defaultCurrency: 'KRW' },
  { name: 'Kakao Pay', slug: 'kakaopay', category: 'Korea' },
  { name: 'Wavve', slug: 'wavve', category: 'Korea', defaultPrice: 10900, defaultCurrency: 'KRW' },
  // --- India (5) ---
  { name: 'Disney+ Hotstar', slug: 'hotstar', category: 'India', defaultPrice: 29900, defaultCurrency: 'INR' },
  { name: 'JioCinema', slug: 'jiocinema', category: 'India', defaultPrice: 2900, defaultCurrency: 'INR' },
  { name: 'Swiggy One', slug: 'swiggy', category: 'India', defaultPrice: 9900, defaultCurrency: 'INR' },
  { name: 'Zomato Gold', slug: 'zomato', category: 'India', defaultPrice: 3000, defaultCurrency: 'INR' },
  { name: 'Flipkart Plus', slug: 'flipkart', category: 'India' },

  // --- Southeast Asia (6) ---
  { name: 'Grab', slug: 'grab', category: 'SoutheastAsia', defaultPrice: 599, defaultCurrency: 'SGD' },
  { name: 'Gojek', slug: 'gojek', category: 'SoutheastAsia', defaultPrice: 49000, defaultCurrency: 'IDR' },
  { name: 'Shopee', slug: 'shopee', category: 'SoutheastAsia' },
  { name: 'Lazada', slug: 'lazada', category: 'SoutheastAsia' },
  { name: 'GCash', slug: 'gcash', category: 'SoutheastAsia' },
  { name: 'LINE', slug: 'line', category: 'SoutheastAsia', defaultPrice: 980, defaultCurrency: 'JPY' },
  // --- Latin America (4) ---
  { name: 'Globoplay', slug: 'globoplay', category: 'LatinAmerica', defaultPrice: 2490, defaultCurrency: 'BRL' },
  { name: 'Mercado Libre', slug: 'mercadolibre', category: 'LatinAmerica', defaultPrice: 1690, defaultCurrency: 'BRL' },
  { name: 'Nubank', slug: 'nubank', category: 'LatinAmerica', defaultPrice: 900, defaultCurrency: 'BRL' },
  { name: 'iFood', slug: 'ifood', category: 'LatinAmerica', defaultPrice: 699, defaultCurrency: 'BRL' },
  // --- Middle East (2) ---
  { name: 'Shahid VIP', slug: 'shahid', category: 'MiddleEast', defaultPrice: 3199, defaultCurrency: 'AED' },
  { name: 'Careem', slug: 'careem', category: 'MiddleEast', defaultPrice: 1999, defaultCurrency: 'AED' },
  // --- Africa (2) ---
  { name: 'Showmax', slug: 'showmax', category: 'Africa', defaultPrice: 3900, defaultCurrency: 'ZAR' },
  { name: 'M-Pesa', slug: 'mpesa', category: 'Africa' },

  // --- Russia (3) ---
  { name: 'Yandex Music', slug: 'yandexmusic', category: 'Russia', defaultPrice: 29900, defaultCurrency: 'RUB' },
  { name: 'Wildberries', slug: 'wildberries', category: 'Russia' },
  { name: 'Ozon Premium', slug: 'ozon', category: 'Russia', defaultPrice: 19900, defaultCurrency: 'RUB' },
]

export const CATEGORIES = [...new Set(POPULAR_SERVICES.map((s) => s.category))]
