/** Comprehensive list of 500+ popular subscription services worldwide */
export interface ServiceTemplate {
  name: string
  slug: string
  category: string
  defaultPrice?: number
  defaultCurrency?: string
}

export const POPULAR_SERVICES: ServiceTemplate[] = [
  // --- Streaming ---
  { name: 'Netflix', slug: 'netflix', category: 'Streaming', defaultPrice: 1599, defaultCurrency: 'USD' },
  { name: 'Disney+', slug: 'disneyplus', category: 'Streaming', defaultPrice: 1399, defaultCurrency: 'USD' },
  { name: 'YouTube Premium', slug: 'youtube', category: 'Streaming', defaultPrice: 1399, defaultCurrency: 'USD' },
  { name: 'Max (HBO)', slug: 'hbo', category: 'Streaming', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Prime Video', slug: 'amazonprimevideo', category: 'Streaming', defaultPrice: 899, defaultCurrency: 'USD' },
  { name: 'Apple TV+', slug: 'appletv', category: 'Streaming', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'Hulu', slug: 'hulu', category: 'Streaming', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Peacock', slug: 'peacock', category: 'Streaming', defaultPrice: 799, defaultCurrency: 'USD' },
  { name: 'Paramount+', slug: 'paramountplus', category: 'Streaming', defaultPrice: 799, defaultCurrency: 'USD' },
  { name: 'Crunchyroll', slug: 'crunchyroll', category: 'Streaming', defaultPrice: 799, defaultCurrency: 'USD' },
  { name: 'ESPN+', slug: 'espn', category: 'Streaming', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Starz', slug: 'starz', category: 'Streaming', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'AMC+', slug: 'amc', category: 'Streaming', defaultPrice: 899, defaultCurrency: 'USD' },
  { name: 'Shudder', slug: 'shudder', category: 'Streaming', defaultPrice: 699, defaultCurrency: 'USD' },
  { name: 'BritBox', slug: 'britbox', category: 'Streaming', defaultPrice: 899, defaultCurrency: 'USD' },
  { name: 'Acorn TV', slug: 'acorntv', category: 'Streaming', defaultPrice: 799, defaultCurrency: 'USD' },
  { name: 'Criterion Channel', slug: 'criterionchannel', category: 'Streaming', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'YouTube TV', slug: 'youtubetv', category: 'Streaming', defaultPrice: 8299, defaultCurrency: 'USD' },
  { name: 'Sling TV', slug: 'slingtv', category: 'Streaming', defaultPrice: 4599, defaultCurrency: 'USD' },
  { name: 'fuboTV', slug: 'fubotv', category: 'Streaming', defaultPrice: 8499, defaultCurrency: 'USD' },
  { name: 'Philo', slug: 'philo', category: 'Streaming', defaultPrice: 2800, defaultCurrency: 'USD' },
  { name: 'MUBI', slug: 'mubi', category: 'Streaming', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'Vimeo', slug: 'vimeo', category: 'Streaming', defaultPrice: 1200, defaultCurrency: 'USD' },
  { name: 'CuriosityStream', slug: 'curiositystream', category: 'Streaming', defaultPrice: 300, defaultCurrency: 'USD' },
  { name: 'Crave', slug: 'crave', category: 'Streaming', defaultPrice: 1199, defaultCurrency: 'CAD' },
  { name: 'Sky', slug: 'sky', category: 'Streaming' },
  { name: 'NOW', slug: 'nowtv', category: 'Streaming' },
  { name: 'Canal+', slug: 'canalplus', category: 'Streaming' },
  { name: 'Joyn+', slug: 'joyn', category: 'Streaming' },
  { name: 'RTL+', slug: 'rtl', category: 'Streaming' },
  { name: 'Viaplay', slug: 'viaplay', category: 'Streaming' },
  { name: 'SkyShowtime', slug: 'skyshowtime', category: 'Streaming' },
  { name: 'Stan', slug: 'stan', category: 'Streaming' },
  { name: 'Binge', slug: 'binge', category: 'Streaming' },
  { name: 'Kayo Sports', slug: 'kayosports', category: 'Streaming' },
  { name: 'Neon NZ', slug: 'neon', category: 'Streaming' },
  { name: 'Viu', slug: 'viu', category: 'Streaming' },
  { name: 'Twitch Turbo', slug: 'twitch', category: 'Streaming', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Kick', slug: 'kick', category: 'Streaming' },
  { name: 'Filmin', slug: 'filmin', category: 'Streaming' },

  // --- Music ---
  { name: 'Spotify', slug: 'spotify', category: 'Music', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Apple Music', slug: 'applemusic', category: 'Music', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'YouTube Music', slug: 'youtubemusic', category: 'Music', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Tidal', slug: 'tidal', category: 'Music', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Amazon Music', slug: 'amazonmusic', category: 'Music', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Deezer', slug: 'deezer', category: 'Music', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'SoundCloud Go+', slug: 'soundcloud', category: 'Music', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Pandora', slug: 'pandora', category: 'Music', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Qobuz', slug: 'qobuz', category: 'Music', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'SiriusXM', slug: 'siriusxm', category: 'Music', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'TuneIn Premium', slug: 'tunein', category: 'Music' },
  { name: 'KKBOX', slug: 'kkbox', category: 'Music' },
  { name: 'JOOX', slug: 'joox', category: 'Music' },
  { name: 'Gaana', slug: 'gaana', category: 'Music' },
  { name: 'JioSaavn', slug: 'jiosaavn', category: 'Music' },
  { name: 'Wynk Music', slug: 'wynk', category: 'Music' },
  { name: 'Boomplay', slug: 'boomplay', category: 'Music' },
  { name: 'Anghami', slug: 'anghami', category: 'Music' },

  // --- Podcasts & Audiobooks ---
  { name: 'Audible', slug: 'audible', category: 'Podcasts', defaultPrice: 1495, defaultCurrency: 'USD' },
  { name: 'Scribd/Everand', slug: 'scribd', category: 'Podcasts', defaultPrice: 1199, defaultCurrency: 'USD' },
  { name: 'Storytel', slug: 'storytel', category: 'Podcasts' },
  { name: 'BookBeat', slug: 'bookbeat', category: 'Podcasts' },
  { name: 'Nextory', slug: 'nextory', category: 'Podcasts' },
  { name: 'Podimo', slug: 'podimo', category: 'Podcasts' },
  { name: 'Luminary', slug: 'luminary', category: 'Podcasts' },
  { name: 'Apple Podcasts Subscriptions', slug: 'applepodcasts', category: 'Podcasts' },
  { name: 'Spotify Podcast Subscriptions', slug: 'spotify', category: 'Podcasts' },
  { name: 'Supercast', slug: 'supercast', category: 'Podcasts' },

  // --- Sports ---
  { name: 'DAZN', slug: 'dazn', category: 'Sports', defaultPrice: 2499, defaultCurrency: 'USD' },
  { name: 'The Athletic', slug: 'theathletic', category: 'Sports', defaultPrice: 799, defaultCurrency: 'USD' },
  { name: 'DraftKings', slug: 'draftkings', category: 'Sports' },
  { name: 'FanDuel', slug: 'fanduel', category: 'Sports' },
  { name: 'Sky Sports', slug: 'sky', category: 'Sports' },
  { name: 'BT Sport / TNT Sports', slug: 'bt', category: 'Sports' },
  { name: 'beIN Sports', slug: 'beinsports', category: 'Sports' },
  { name: 'SuperSport', slug: 'supersport', category: 'Sports' },

  // --- AI Tools ---
  { name: 'ChatGPT Plus', slug: 'openai', category: 'AI', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'ChatGPT Pro', slug: 'openai', category: 'AI', defaultPrice: 20000, defaultCurrency: 'USD' },
  { name: 'Claude Pro', slug: 'claude', category: 'AI', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'Claude Max', slug: 'claude', category: 'AI', defaultPrice: 10000, defaultCurrency: 'USD' },
  { name: 'Gemini Advanced', slug: 'googlegemini', category: 'AI', defaultPrice: 1999, defaultCurrency: 'USD' },
  { name: 'Microsoft Copilot Pro', slug: 'microsoftcopilot', category: 'AI', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'Perplexity Pro', slug: 'perplexity', category: 'AI', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'Poe', slug: 'poe', category: 'AI', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'Midjourney', slug: 'midjourney', category: 'AI', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'DALL-E', slug: 'openai', category: 'AI' },
  { name: 'Leonardo.ai', slug: 'leonardoai', category: 'AI', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'Runway ML', slug: 'runwayml', category: 'AI', defaultPrice: 1200, defaultCurrency: 'USD' },
  { name: 'Pika', slug: 'pika', category: 'AI' },
  { name: 'Sora', slug: 'openai', category: 'AI' },
  { name: 'Synthesia', slug: 'synthesia', category: 'AI' },
  { name: 'HeyGen', slug: 'heygen', category: 'AI' },
  { name: 'ElevenLabs', slug: 'elevenlabs', category: 'AI', defaultPrice: 2200, defaultCurrency: 'USD' },
  { name: 'Suno AI', slug: 'suno', category: 'AI', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'Udio', slug: 'udio', category: 'AI' },
  { name: 'Jasper AI', slug: 'jasper', category: 'AI', defaultPrice: 3900, defaultCurrency: 'USD' },
  { name: 'Copy.ai', slug: 'copyai', category: 'AI' },
  { name: 'Grammarly Premium', slug: 'grammarly', category: 'AI', defaultPrice: 1200, defaultCurrency: 'USD' },
  { name: 'DeepL Pro', slug: 'deepl', category: 'AI', defaultPrice: 1049, defaultCurrency: 'USD' },
  { name: 'Otter.ai', slug: 'otter', category: 'AI', defaultPrice: 1699, defaultCurrency: 'USD' },
  { name: 'Fireflies.ai', slug: 'fireflies', category: 'AI' },
  { name: 'Descript', slug: 'descript', category: 'AI', defaultPrice: 1200, defaultCurrency: 'USD' },
  { name: 'Notion AI', slug: 'notion', category: 'AI' },

  // --- Developer Tools ---
  { name: 'GitHub Pro', slug: 'github', category: 'Developer', defaultPrice: 400, defaultCurrency: 'USD' },
  { name: 'GitHub Copilot', slug: 'githubcopilot', category: 'Developer', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'GitLab Premium', slug: 'gitlab', category: 'Developer', defaultPrice: 2900, defaultCurrency: 'USD' },
  { name: 'Bitbucket', slug: 'bitbucket', category: 'Developer' },
  { name: 'JetBrains All Products', slug: 'jetbrains', category: 'Developer', defaultPrice: 2490, defaultCurrency: 'USD' },
  { name: 'Replit', slug: 'replit', category: 'Developer' },
  { name: 'CodeSandbox', slug: 'codesandbox', category: 'Developer' },
  { name: 'Gitpod', slug: 'gitpod', category: 'Developer' },
  { name: 'Postman', slug: 'postman', category: 'Developer' },
  { name: 'Docker Pro', slug: 'docker', category: 'Developer', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'GitKraken', slug: 'gitkraken', category: 'Developer' },
  { name: 'Cursor Pro', slug: 'cursor', category: 'Developer', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'Windsurf / Codeium', slug: 'codeium', category: 'Developer' },
  { name: 'Tabnine', slug: 'tabnine', category: 'Developer' },
  { name: 'Claude Code', slug: 'claude', category: 'Developer' },
  { name: 'Devin', slug: 'cognition', category: 'Developer' },
  { name: 'Vercel Pro', slug: 'vercel', category: 'Developer', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'Netlify Pro', slug: 'netlify', category: 'Developer', defaultPrice: 1900, defaultCurrency: 'USD' },
  { name: 'Railway', slug: 'railway', category: 'Developer' },
  { name: 'Render', slug: 'render', category: 'Developer' },
  { name: 'Heroku', slug: 'heroku', category: 'Developer' },
  { name: 'Fly.io', slug: 'flydotio', category: 'Developer' },
  { name: 'DigitalOcean', slug: 'digitalocean', category: 'Developer' },
  { name: 'Supabase', slug: 'supabase', category: 'Developer', defaultPrice: 2500, defaultCurrency: 'USD' },
  { name: 'PlanetScale', slug: 'planetscale', category: 'Developer' },
  { name: 'Neon', slug: 'neon', category: 'Developer' },
  { name: 'MongoDB Atlas', slug: 'mongodb', category: 'Developer' },
  { name: 'Cloudflare', slug: 'cloudflare', category: 'Developer' },
  { name: 'Sentry', slug: 'sentry', category: 'Developer' },
  { name: 'Datadog', slug: 'datadog', category: 'Developer' },
  { name: 'New Relic', slug: 'newrelic', category: 'Developer' },
  { name: 'LeetCode', slug: 'leetcode', category: 'Developer' },
  { name: 'HackerRank', slug: 'hackerrank', category: 'Developer' },
  { name: 'Tailscale', slug: 'tailscale', category: 'Developer', defaultPrice: 600, defaultCurrency: 'USD' },

  // --- Productivity ---
  { name: 'Microsoft 365', slug: 'microsoftoffice', category: 'Productivity', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Google Workspace', slug: 'google', category: 'Productivity', defaultPrice: 600, defaultCurrency: 'USD' },
  { name: 'Notion', slug: 'notion', category: 'Productivity', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'Obsidian Sync', slug: 'obsidian', category: 'Productivity', defaultPrice: 400, defaultCurrency: 'USD' },
  { name: 'Roam Research', slug: 'roamresearch', category: 'Productivity' },
  { name: 'Bear Pro', slug: 'bear', category: 'Productivity' },
  { name: 'Ulysses', slug: 'ulysses', category: 'Productivity' },
  { name: 'Craft', slug: 'craft', category: 'Productivity' },
  { name: 'Heptabase', slug: 'heptabase', category: 'Productivity' },
  { name: 'Evernote', slug: 'evernote', category: 'Productivity', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'Day One', slug: 'dayone', category: 'Productivity' },
  { name: 'Standard Notes', slug: 'standardnotes', category: 'Productivity' },
  { name: 'Coda', slug: 'coda', category: 'Productivity', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'Airtable', slug: 'airtable', category: 'Productivity', defaultPrice: 2000, defaultCurrency: 'USD' },
  { name: 'Trello', slug: 'trello', category: 'Productivity', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'Asana', slug: 'asana', category: 'Productivity', defaultPrice: 1099, defaultCurrency: 'USD' },
  { name: 'Monday.com', slug: 'mondaydotcom', category: 'Productivity' },
  { name: 'Jira', slug: 'jira', category: 'Productivity' },
  { name: 'Linear', slug: 'linear', category: 'Productivity', defaultPrice: 800, defaultCurrency: 'USD' },
  { name: 'ClickUp', slug: 'clickup', category: 'Productivity', defaultPrice: 700, defaultCurrency: 'USD' },
  { name: 'Basecamp', slug: 'basecamp', category: 'Productivity' },
  { name: 'Confluence', slug: 'confluence', category: 'Productivity' },
  { name: 'Todoist Pro', slug: 'todoist', category: 'Productivity', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'Raycast Pro', slug: 'raycast', category: 'Productivity', defaultPrice: 800, defaultCurrency: 'USD' },
  { name: 'Setapp', slug: 'setapp', category: 'Productivity', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'TextExpander', slug: 'textexpander', category: 'Productivity' },
  { name: 'Superhuman', slug: 'superhuman', category: 'Productivity', defaultPrice: 3000, defaultCurrency: 'USD' },
  { name: 'Toggl Track', slug: 'toggl', category: 'Productivity' },
  { name: 'Fantastical', slug: 'fantastical', category: 'Productivity' },
  { name: 'Calendly', slug: 'calendly', category: 'Productivity' },
  { name: 'Cal.com', slug: 'caldotcom', category: 'Productivity' },
  { name: 'Reclaim.ai', slug: 'reclaim', category: 'Productivity' },
  { name: 'IFTTT', slug: 'ifttt', category: 'Productivity' },
  { name: 'Zapier', slug: 'zapier', category: 'Productivity' },
  { name: 'Make', slug: 'make', category: 'Productivity' },
  { name: 'WPS Office', slug: 'wps', category: 'Productivity' },
  { name: 'GoodNotes', slug: 'goodnotes', category: 'Productivity' },
  { name: 'Miro', slug: 'miro', category: 'Productivity', defaultPrice: 800, defaultCurrency: 'USD' },
  { name: 'Loom', slug: 'loom', category: 'Productivity', defaultPrice: 1250, defaultCurrency: 'USD' },

  // --- Design & Creative ---
  { name: 'Adobe Creative Cloud', slug: 'adobecreativecloud', category: 'Design', defaultPrice: 5999, defaultCurrency: 'USD' },
  { name: 'Adobe Photoshop', slug: 'adobephotoshop', category: 'Design', defaultPrice: 2299, defaultCurrency: 'USD' },
  { name: 'Adobe Lightroom', slug: 'adobelightroom', category: 'Design', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Adobe Premiere Pro', slug: 'adobepremierepro', category: 'Design', defaultPrice: 2299, defaultCurrency: 'USD' },
  { name: 'Adobe Illustrator', slug: 'adobeillustrator', category: 'Design' },
  { name: 'Adobe After Effects', slug: 'adobeaftereffects', category: 'Design' },
  { name: 'Figma', slug: 'figma', category: 'Design', defaultPrice: 1500, defaultCurrency: 'USD' },
  { name: 'FigJam', slug: 'figma', category: 'Design' },
  { name: 'Canva Pro', slug: 'canva', category: 'Design', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'Sketch', slug: 'sketch', category: 'Design', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'Framer', slug: 'framer', category: 'Design', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'Whimsical', slug: 'whimsical', category: 'Design' },
  { name: 'Lucidchart', slug: 'lucidchart', category: 'Design' },
  { name: 'Spline', slug: 'spline', category: 'Design' },
  { name: 'SketchUp', slug: 'sketchup', category: 'Design' },
  { name: 'CapCut Pro', slug: 'capcut', category: 'Design', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'DaVinci Resolve Studio', slug: 'davinciresolve', category: 'Design' },
  { name: 'Pixelmator Pro', slug: 'pixelmator', category: 'Design' },
  { name: 'Affinity V2', slug: 'affinity', category: 'Design' },
  { name: 'Shutterstock', slug: 'shutterstock', category: 'Design' },
  { name: 'Getty Images', slug: 'gettyimages', category: 'Design' },
  { name: 'Adobe Stock', slug: 'adobe', category: 'Design' },
  { name: 'iStock', slug: 'istock', category: 'Design' },
  { name: 'Envato Elements', slug: 'envato', category: 'Design', defaultPrice: 1650, defaultCurrency: 'USD' },
  { name: 'Artlist', slug: 'artlist', category: 'Design' },
  { name: 'Epidemic Sound', slug: 'epidemicsound', category: 'Design' },
  { name: 'Storyblocks', slug: 'storyblocks', category: 'Design' },
  { name: 'Unsplash+', slug: 'unsplash', category: 'Design' },

  // --- Cloud Storage ---
  { name: 'iCloud+', slug: 'icloud', category: 'Cloud', defaultPrice: 99, defaultCurrency: 'USD' },
  { name: 'Google One', slug: 'google', category: 'Cloud', defaultPrice: 199, defaultCurrency: 'USD' },
  { name: 'Dropbox Plus', slug: 'dropbox', category: 'Cloud', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'OneDrive', slug: 'microsoftonedrive', category: 'Cloud', defaultPrice: 199, defaultCurrency: 'USD' },
  { name: 'Google Drive', slug: 'googledrive', category: 'Cloud' },
  { name: 'pCloud', slug: 'pcloud', category: 'Cloud', defaultPrice: 499, defaultCurrency: 'USD' },
  { name: 'MEGA', slug: 'mega', category: 'Cloud', defaultPrice: 535, defaultCurrency: 'USD' },
  { name: 'Tresorit', slug: 'tresorit', category: 'Cloud' },
  { name: 'Backblaze', slug: 'backblaze', category: 'Cloud', defaultPrice: 900, defaultCurrency: 'USD' },
  { name: 'Proton Drive', slug: 'protondrive', category: 'Cloud' },

  // --- VPN ---
  { name: 'NordVPN', slug: 'nordvpn', category: 'VPN', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'ExpressVPN', slug: 'expressvpn', category: 'VPN', defaultPrice: 1295, defaultCurrency: 'USD' },
  { name: 'Surfshark', slug: 'surfshark', category: 'VPN', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'ProtonVPN', slug: 'protonvpn', category: 'VPN', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Mullvad VPN', slug: 'mullvad', category: 'VPN', defaultPrice: 546, defaultCurrency: 'USD' },

  // --- Security ---
  { name: '1Password', slug: '1password', category: 'Security', defaultPrice: 299, defaultCurrency: 'USD' },
  { name: 'Bitwarden Premium', slug: 'bitwarden', category: 'Security', defaultPrice: 83, defaultCurrency: 'USD' },
  { name: 'Dashlane', slug: 'dashlane', category: 'Security', defaultPrice: 499, defaultCurrency: 'USD' },
  { name: 'LastPass Premium', slug: 'lastpass', category: 'Security', defaultPrice: 300, defaultCurrency: 'USD' },
  { name: 'Norton 360', slug: 'norton', category: 'Security' },
  { name: 'Bitdefender', slug: 'bitdefender', category: 'Security' },
  { name: 'Experian', slug: 'experian', category: 'Security' },
  { name: 'LifeLock', slug: 'lifelock', category: 'Security' },
  { name: 'myFICO', slug: 'myfico', category: 'Security' },
  { name: 'Aura', slug: 'aura', category: 'Security' },
  { name: 'Proton Unlimited', slug: 'proton', category: 'Security', defaultPrice: 999, defaultCurrency: 'USD' },

  // --- Communication ---
  { name: 'Slack Pro', slug: 'slack', category: 'Communication', defaultPrice: 875, defaultCurrency: 'USD' },
  { name: 'Zoom', slug: 'zoom', category: 'Communication', defaultPrice: 1333, defaultCurrency: 'USD' },
  { name: 'Microsoft Teams', slug: 'microsoftteams', category: 'Communication' },
  { name: 'Discord Nitro', slug: 'discord', category: 'Communication', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Telegram Premium', slug: 'telegram', category: 'Communication', defaultPrice: 499, defaultCurrency: 'USD' },
  { name: 'WhatsApp', slug: 'whatsapp', category: 'Communication' },
  { name: 'Signal', slug: 'signal', category: 'Communication' },

  // --- Email ---
  { name: 'Proton Mail Plus', slug: 'protonmail', category: 'Email', defaultPrice: 399, defaultCurrency: 'USD' },
  { name: 'HEY', slug: 'hey', category: 'Email' },
  { name: 'Fastmail', slug: 'fastmail', category: 'Email', defaultPrice: 300, defaultCurrency: 'USD' },
  { name: 'Tuta / Tutanota', slug: 'tutanota', category: 'Email' },
  { name: 'Zoho Mail', slug: 'zoho', category: 'Email' },

  // --- Social ---
  { name: 'X Premium', slug: 'x', category: 'Social', defaultPrice: 800, defaultCurrency: 'USD' },
  { name: 'LinkedIn Premium', slug: 'linkedin', category: 'Social', defaultPrice: 2999, defaultCurrency: 'USD' },
  { name: 'Reddit Premium', slug: 'reddit', category: 'Social', defaultPrice: 599, defaultCurrency: 'USD' },
  { name: 'Snapchat+', slug: 'snapchat', category: 'Social', defaultPrice: 399, defaultCurrency: 'USD' },
  { name: 'Meta Verified', slug: 'meta', category: 'Social' },
  { name: 'Instagram', slug: 'instagram', category: 'Social' },
  { name: 'Pinterest', slug: 'pinterest', category: 'Social' },
  { name: 'Quora+', slug: 'quora', category: 'Social' },

  // --- Dating ---
  { name: 'Tinder Plus/Gold/Platinum', slug: 'tinder', category: 'Dating', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Bumble Premium', slug: 'bumble', category: 'Dating', defaultPrice: 1699, defaultCurrency: 'USD' },
  { name: 'Hinge Preferred', slug: 'hinge', category: 'Dating', defaultPrice: 2999, defaultCurrency: 'USD' },
  { name: 'Match.com', slug: 'matchdotcom', category: 'Dating' },
  { name: 'OkCupid', slug: 'okcupid', category: 'Dating' },
  { name: 'Grindr', slug: 'grindr', category: 'Dating' },
  { name: 'Feeld', slug: 'feeld', category: 'Dating' },
  { name: 'Coffee Meets Bagel', slug: 'coffeemeetsbagel', category: 'Dating' },

  // --- Gaming ---
  { name: 'Xbox Game Pass Ultimate', slug: 'xbox', category: 'Gaming', defaultPrice: 2999, defaultCurrency: 'USD' },
  { name: 'Xbox Game Pass PC', slug: 'xbox', category: 'Gaming', defaultPrice: 1649, defaultCurrency: 'USD' },
  { name: 'PlayStation Plus Essential', slug: 'playstation', category: 'Gaming', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'PlayStation Plus Extra', slug: 'playstation', category: 'Gaming', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'PlayStation Plus Premium', slug: 'playstation', category: 'Gaming', defaultPrice: 1799, defaultCurrency: 'USD' },
  { name: 'Nintendo Switch Online', slug: 'nintendoswitch', category: 'Gaming', defaultPrice: 399, defaultCurrency: 'USD' },
  { name: 'EA Play', slug: 'ea', category: 'Gaming', defaultPrice: 599, defaultCurrency: 'USD' },
  { name: 'Ubisoft+', slug: 'ubisoft', category: 'Gaming', defaultPrice: 1799, defaultCurrency: 'USD' },
  { name: 'Humble Choice', slug: 'humblebundle', category: 'Gaming' },
  { name: 'GeForce NOW', slug: 'nvidia', category: 'Gaming', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Apple Arcade', slug: 'apple', category: 'Gaming', defaultPrice: 699, defaultCurrency: 'USD' },
  { name: 'Google Play Pass', slug: 'googleplay', category: 'Gaming' },
  { name: 'Amazon Luna', slug: 'amazonluna', category: 'Gaming' },
  { name: 'Shadow PC', slug: 'shadow', category: 'Gaming' },
  { name: 'Boosteroid', slug: 'boosteroid', category: 'Gaming' },
  { name: 'Blacknut', slug: 'blacknut', category: 'Gaming' },
  { name: 'World of Warcraft', slug: 'worldofwarcraft', category: 'Gaming' },
  { name: 'Final Fantasy XIV', slug: 'finalfantasy', category: 'Gaming' },
  { name: 'ESO Plus', slug: 'elderscrollsonline', category: 'Gaming' },
  { name: 'RuneScape', slug: 'runescape', category: 'Gaming' },
  { name: 'EVE Online Omega', slug: 'eveonline', category: 'Gaming' },
  { name: 'Fortnite Crew', slug: 'fortnite', category: 'Gaming' },
  { name: 'Dota Plus', slug: 'dota2', category: 'Gaming' },
  { name: 'Roblox Premium', slug: 'roblox', category: 'Gaming' },
  { name: 'Minecraft Realms', slug: 'minecraft', category: 'Gaming' },

  // --- Education ---
  { name: 'Coursera Plus', slug: 'coursera', category: 'Education', defaultPrice: 5900, defaultCurrency: 'USD' },
  { name: 'Udemy', slug: 'udemy', category: 'Education' },
  { name: 'edX', slug: 'edx', category: 'Education' },
  { name: 'LinkedIn Learning', slug: 'linkedin', category: 'Education', defaultPrice: 2999, defaultCurrency: 'USD' },
  { name: 'Skillshare', slug: 'skillshare', category: 'Education', defaultPrice: 1400, defaultCurrency: 'USD' },
  { name: 'MasterClass', slug: 'masterclass', category: 'Education', defaultPrice: 1000, defaultCurrency: 'USD' },
  { name: 'Pluralsight', slug: 'pluralsight', category: 'Education' },
  { name: 'DataCamp', slug: 'datacamp', category: 'Education' },
  { name: 'Codecademy Pro', slug: 'codecademy', category: 'Education' },
  { name: "O'Reilly", slug: 'oreilly', category: 'Education' },
  { name: 'Frontend Masters', slug: 'frontendmasters', category: 'Education' },
  { name: 'Brilliant', slug: 'brilliant', category: 'Education', defaultPrice: 1249, defaultCurrency: 'USD' },
  { name: 'Duolingo Super', slug: 'duolingo', category: 'Education', defaultPrice: 699, defaultCurrency: 'USD' },
  { name: 'Duolingo Max', slug: 'duolingo', category: 'Education', defaultPrice: 2999, defaultCurrency: 'USD' },
  { name: 'Babbel', slug: 'babbel', category: 'Education' },
  { name: 'Rosetta Stone', slug: 'rosettastone', category: 'Education' },
  { name: 'Busuu', slug: 'busuu', category: 'Education' },
  { name: 'Pimsleur', slug: 'pimsleur', category: 'Education' },
  { name: 'italki', slug: 'italki', category: 'Education' },
  { name: 'Preply', slug: 'preply', category: 'Education' },
  { name: 'Memrise', slug: 'memrise', category: 'Education' },
  { name: 'ELSA Speak', slug: 'elsaspeak', category: 'Education' },
  { name: 'ABCmouse', slug: 'abcmouse', category: 'Education' },
  { name: 'IXL', slug: 'ixl', category: 'Education' },
  { name: 'Khan Academy', slug: 'khanacademy', category: 'Education' },
  { name: 'Yousician', slug: 'yousician', category: 'Education' },
  { name: 'Simply Piano', slug: 'simplypiano', category: 'Education' },
  { name: 'Flowkey', slug: 'flowkey', category: 'Education' },
  { name: 'Overleaf', slug: 'overleaf', category: 'Education' },
  { name: 'JSTOR', slug: 'jstor', category: 'Education' },

  // --- Reading ---
  { name: 'Medium', slug: 'medium', category: 'Reading', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'Substack', slug: 'substack', category: 'Reading' },
  { name: 'The New York Times', slug: 'newyorktimes', category: 'Reading', defaultPrice: 1700, defaultCurrency: 'USD' },
  { name: 'Wall Street Journal', slug: 'wsj', category: 'Reading' },
  { name: 'Washington Post', slug: 'thewashingtonpost', category: 'Reading' },
  { name: 'Financial Times', slug: 'financialtimes', category: 'Reading' },
  { name: 'Bloomberg', slug: 'bloomberg', category: 'Reading' },
  { name: 'The Economist', slug: 'economist', category: 'Reading', defaultPrice: 1400, defaultCurrency: 'USD' },
  { name: 'The Atlantic', slug: 'theatlantic', category: 'Reading' },
  { name: 'The New Yorker', slug: 'thenewyorker', category: 'Reading' },
  { name: 'Wired', slug: 'wired', category: 'Reading' },
  { name: 'The Information', slug: 'theinformation', category: 'Reading' },
  { name: 'Stratechery', slug: 'stratechery', category: 'Reading' },
  { name: "Lenny's Newsletter", slug: 'substack', category: 'Reading' },
  { name: 'The Times (UK)', slug: 'thetimes', category: 'Reading' },
  { name: 'The Guardian', slug: 'theguardian', category: 'Reading' },
  { name: 'Kindle Unlimited', slug: 'amazon', category: 'Reading', defaultPrice: 1199, defaultCurrency: 'USD' },
  { name: 'Apple News+', slug: 'apple', category: 'Reading', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'Readly', slug: 'readly', category: 'Reading' },
  { name: 'Magzter Gold', slug: 'magzter', category: 'Reading' },
  { name: 'PressReader', slug: 'pressreader', category: 'Reading' },
  { name: 'Readwise', slug: 'readwise', category: 'Reading' },
  { name: 'Pocket Premium', slug: 'pocket', category: 'Reading' },
  { name: 'Instapaper', slug: 'instapaper', category: 'Reading' },
  { name: 'Feedly Pro', slug: 'feedly', category: 'Reading', defaultPrice: 600, defaultCurrency: 'USD' },
  { name: 'Inoreader', slug: 'inoreader', category: 'Reading' },

  // --- Fitness ---
  { name: 'Peloton App', slug: 'peloton', category: 'Fitness', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'Apple Fitness+', slug: 'apple', category: 'Fitness', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Strava Premium', slug: 'strava', category: 'Fitness', defaultPrice: 1199, defaultCurrency: 'USD' },
  { name: 'Fitbit Premium', slug: 'fitbit', category: 'Fitness', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'WHOOP', slug: 'whoop', category: 'Fitness', defaultPrice: 3000, defaultCurrency: 'USD' },
  { name: 'Oura Ring', slug: 'oura', category: 'Fitness' },
  { name: 'Freeletics', slug: 'freeletics', category: 'Fitness' },
  { name: 'ClassPass', slug: 'classpass', category: 'Fitness' },
  { name: 'Gympass / Wellhub', slug: 'wellhub', category: 'Fitness' },
  { name: 'Les Mills+', slug: 'lesmills', category: 'Fitness' },
  { name: 'Centr', slug: 'centr', category: 'Fitness' },
  { name: 'Alo Moves', slug: 'alomoves', category: 'Fitness' },
  { name: 'Nike Training Club', slug: 'nike', category: 'Fitness' },
  { name: 'MyFitnessPal Premium', slug: 'myfitnesspal', category: 'Fitness', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'AllTrails Pro', slug: 'alltrails', category: 'Fitness' },

  // --- Health ---
  { name: 'Calm', slug: 'calm', category: 'Health', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'Headspace', slug: 'headspace', category: 'Health', defaultPrice: 1299, defaultCurrency: 'USD' },
  { name: 'Waking Up', slug: 'wakingup', category: 'Health' },
  { name: 'Ten Percent Happier', slug: 'tenpercent', category: 'Health' },
  { name: 'BetterHelp', slug: 'betterhelp', category: 'Health' },
  { name: 'Talkspace', slug: 'talkspace', category: 'Health' },
  { name: 'Noom', slug: 'noom', category: 'Health', defaultPrice: 5900, defaultCurrency: 'USD' },
  { name: 'WW (WeightWatchers)', slug: 'weightwatchers', category: 'Health' },
  { name: 'Flo Premium', slug: 'flo', category: 'Health' },
  { name: 'Clue Plus', slug: 'clue', category: 'Health' },
  { name: 'Natural Cycles', slug: 'naturalcycles', category: 'Health' },
  { name: 'Hims', slug: 'hims', category: 'Health' },
  { name: 'Hers', slug: 'hers', category: 'Health' },
  { name: 'Ro', slug: 'ro', category: 'Health' },
  { name: 'Teladoc', slug: 'teladoc', category: 'Health' },
  { name: 'One Medical', slug: 'onemedical', category: 'Health' },
  { name: 'Lifesum', slug: 'lifesum', category: 'Health' },

  // --- Shopping & Delivery ---
  { name: 'Amazon Prime', slug: 'amazonprime', category: 'Shopping', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'Walmart+', slug: 'walmart', category: 'Shopping', defaultPrice: 1295, defaultCurrency: 'USD' },
  { name: 'Target Circle 360', slug: 'target', category: 'Shopping' },
  { name: 'Costco', slug: 'costco', category: 'Shopping' },
  { name: "Sam's Club", slug: 'samsclub', category: 'Shopping' },
  { name: 'DoorDash DashPass', slug: 'doordash', category: 'Shopping', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Uber One', slug: 'uber', category: 'Shopping', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Grubhub+', slug: 'grubhub', category: 'Shopping' },
  { name: 'Deliveroo Plus', slug: 'deliveroo', category: 'Shopping' },
  { name: 'Instacart+', slug: 'instacart', category: 'Shopping', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'Thrive Market', slug: 'thrivemarket', category: 'Shopping' },
  { name: 'HelloFresh', slug: 'hellofresh', category: 'Shopping' },
  { name: 'Blue Apron', slug: 'blueapron', category: 'Shopping' },
  { name: 'Home Chef', slug: 'homechef', category: 'Shopping' },
  { name: 'Factor', slug: 'factor', category: 'Shopping' },
  { name: 'Daily Harvest', slug: 'dailyharvest', category: 'Shopping' },
  { name: 'Dollar Shave Club', slug: 'dollarshaveclub', category: 'Shopping' },
  { name: "Harry's", slug: 'harrys', category: 'Shopping' },
  { name: 'Birchbox', slug: 'birchbox', category: 'Shopping' },
  { name: 'Ipsy', slug: 'ipsy', category: 'Shopping' },
  { name: 'BoxyCharm', slug: 'boxycharm', category: 'Shopping' },
  { name: 'Rent the Runway', slug: 'renttherunway', category: 'Shopping' },
  { name: 'Stitch Fix', slug: 'stitchfix', category: 'Shopping' },
  { name: 'FabFitFun', slug: 'fabfitfun', category: 'Shopping' },
  { name: 'BarkBox', slug: 'barkbox', category: 'Shopping' },
  { name: "Farmer's Dog", slug: 'farmersdog', category: 'Shopping' },
  { name: 'Rappi Prime', slug: 'rappi', category: 'Shopping' },
  { name: 'foodpanda Pro', slug: 'foodpanda', category: 'Shopping' },

  // --- Finance ---
  { name: 'TradingView', slug: 'tradingview', category: 'Finance', defaultPrice: 1495, defaultCurrency: 'USD' },
  { name: 'Morningstar Premium', slug: 'morningstar', category: 'Finance' },
  { name: 'Seeking Alpha', slug: 'seekingalpha', category: 'Finance' },
  { name: 'Motley Fool', slug: 'motleyfool', category: 'Finance' },
  { name: 'YNAB', slug: 'ynab', category: 'Finance', defaultPrice: 1499, defaultCurrency: 'USD' },
  { name: 'Monarch Money', slug: 'monarchmoney', category: 'Finance' },
  { name: 'Quicken', slug: 'quicken', category: 'Finance' },
  { name: 'Copilot Money', slug: 'copilotmoney', category: 'Finance' },
  { name: 'Robinhood Gold', slug: 'robinhood', category: 'Finance', defaultPrice: 500, defaultCurrency: 'USD' },
  { name: 'Coinbase One', slug: 'coinbase', category: 'Finance', defaultPrice: 2999, defaultCurrency: 'USD' },
  { name: 'CoinGecko Premium', slug: 'coingecko', category: 'Finance' },
  { name: 'Revolut Premium', slug: 'revolut', category: 'Finance', defaultPrice: 999, defaultCurrency: 'USD' },
  { name: 'N26', slug: 'n26', category: 'Finance' },
  { name: 'Monzo Plus', slug: 'monzo', category: 'Finance' },
  { name: 'Wise Premium', slug: 'wise', category: 'Finance' },
  { name: 'Crunchbase Pro', slug: 'crunchbase', category: 'Finance' },
  { name: 'PitchBook', slug: 'pitchbook', category: 'Finance' },
  { name: 'Statista', slug: 'statista', category: 'Finance' },

  // --- Creator Economy ---
  { name: 'Patreon', slug: 'patreon', category: 'Creator' },
  { name: 'Ko-fi', slug: 'kofi', category: 'Creator' },
  { name: 'Buy Me a Coffee', slug: 'buymeacoffee', category: 'Creator' },
  { name: 'OnlyFans', slug: 'onlyfans', category: 'Creator' },
  { name: 'Fansly', slug: 'fansly', category: 'Creator' },
  { name: 'Gumroad', slug: 'gumroad', category: 'Creator' },
  { name: 'Bandcamp', slug: 'bandcamp', category: 'Creator' },
  { name: 'DistroKid', slug: 'distrokid', category: 'Creator' },
  { name: 'Memberful', slug: 'memberful', category: 'Creator' },
  { name: 'Ghost Pro', slug: 'ghost', category: 'Creator' },
  { name: 'Squarespace', slug: 'squarespace', category: 'Creator' },
  { name: 'Wix', slug: 'wix', category: 'Creator' },
  { name: 'Webflow', slug: 'webflow', category: 'Creator' },
  { name: 'Shopify', slug: 'shopify', category: 'Creator', defaultPrice: 2900, defaultCurrency: 'USD' },
  { name: 'Teachable', slug: 'teachable', category: 'Creator' },
  { name: 'Mailchimp', slug: 'mailchimp', category: 'Creator' },
  { name: 'Beehiiv', slug: 'beehiiv', category: 'Creator' },
  { name: 'ConvertKit', slug: 'convertkit', category: 'Creator' },

  // --- Weather & Outdoor ---
  { name: 'Windy Premium', slug: 'windy', category: 'Weather' },
  { name: 'AccuWeather Premium', slug: 'accuweather', category: 'Weather' },
  { name: 'Carrot Weather', slug: 'carrotweather', category: 'Weather' },
  { name: 'RadarScope', slug: 'radarscope', category: 'Weather' },
  { name: 'Gaia GPS Pro', slug: 'gaiagps', category: 'Weather' },
  { name: 'onX Maps', slug: 'onx', category: 'Weather' },

  // --- China ---
  { name: '爱奇艺 iQIYI', slug: 'iqiyi', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '优酷 Youku', slug: 'youku', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '腾讯视频', slug: 'tencentvideo', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '芒果TV', slug: 'mangotv', category: 'China', defaultPrice: 1900, defaultCurrency: 'CNY' },
  { name: 'bilibili 大会员', slug: 'bilibili', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '搜狐视频', slug: 'sohu', category: 'China' },
  { name: '咪咕视频', slug: 'migu', category: 'China' },
  { name: '西瓜视频', slug: 'xigua', category: 'China' },
  { name: 'QQ音乐', slug: 'qqmusic', category: 'China', defaultPrice: 1500, defaultCurrency: 'CNY' },
  { name: '网易云音乐', slug: 'neteasecloudmusic', category: 'China', defaultPrice: 1500, defaultCurrency: 'CNY' },
  { name: '酷狗音乐', slug: 'kugou', category: 'China' },
  { name: '酷我音乐', slug: 'kuwo', category: 'China' },
  { name: '咪咕音乐', slug: 'migumusic', category: 'China' },
  { name: '全民K歌', slug: 'quanmin', category: 'China' },
  { name: '知乎盐选', slug: 'zhihu', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '得到', slug: 'dedao', category: 'China' },
  { name: '喜马拉雅', slug: 'ximalaya', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '蜻蜓FM', slug: 'qingtingfm', category: 'China' },
  { name: '荔枝FM', slug: 'lizhi', category: 'China' },
  { name: '微信读书', slug: 'weread', category: 'China' },
  { name: '掌阅 iReader', slug: 'ireader', category: 'China' },
  { name: '起点读书', slug: 'qidian', category: 'China' },
  { name: '番茄小说', slug: 'fanqie', category: 'China' },
  { name: '七猫小说', slug: 'qimao', category: 'China' },
  { name: '京东读书', slug: 'jingdongdushu', category: 'China' },
  { name: '樊登读书', slug: 'fandeng', category: 'China' },
  { name: '淘宝 88VIP', slug: 'taobao', category: 'China', defaultPrice: 7400, defaultCurrency: 'CNY' },
  { name: '京东 PLUS', slug: 'jd', category: 'China', defaultPrice: 1242, defaultCurrency: 'CNY' },
  { name: '拼多多省钱月卡', slug: 'pinduoduo', category: 'China' },
  { name: '苏宁 Super', slug: 'suning', category: 'China' },
  { name: '唯品会超级VIP', slug: 'vipshop', category: 'China' },
  { name: '美团神会员', slug: 'meituan', category: 'China' },
  { name: '饿了么超级会员', slug: 'eleme', category: 'China', defaultPrice: 1500, defaultCurrency: 'CNY' },
  { name: '盒马X会员', slug: 'hema', category: 'China' },
  { name: '叮咚买菜绿卡', slug: 'dingdong', category: 'China' },
  { name: '瑞幸月卡', slug: 'luckincoffee', category: 'China' },
  { name: '滴滴橙长会员', slug: 'didi', category: 'China' },
  { name: '哈啰骑行卡', slug: 'hello', category: 'China' },
  { name: '美团单车月卡', slug: 'meituanbike', category: 'China' },
  { name: '携程超级会员', slug: 'ctrip', category: 'China' },
  { name: '飞猪', slug: 'fliggy', category: 'China' },
  { name: '百度网盘超级会员', slug: 'baidupan', category: 'China', defaultPrice: 2500, defaultCurrency: 'CNY' },
  { name: '夸克网盘', slug: 'quark', category: 'China' },
  { name: '阿里云盘', slug: 'aliyunpan', category: 'China' },
  { name: '腾讯微云', slug: 'weiyun', category: 'China' },
  { name: '迅雷超级会员', slug: 'xunlei', category: 'China' },
  { name: 'WPS 会员', slug: 'wps', category: 'China' },
  { name: '有道云笔记', slug: 'youdao', category: 'China' },
  { name: '石墨文档', slug: 'shimo', category: 'China' },
  { name: '语雀', slug: 'yuque', category: 'China' },
  { name: 'flomo Pro', slug: 'flomo', category: 'China' },
  { name: '坚果云', slug: 'jianguoyun', category: 'China' },
  { name: '微博 VIP/SVIP', slug: 'sinaweibo', category: 'China', defaultPrice: 1200, defaultCurrency: 'CNY' },
  { name: 'QQ超级会员', slug: 'tencentqq', category: 'China' },
  { name: '陌陌VIP', slug: 'momo', category: 'China' },
  { name: '探探VIP', slug: 'tantan', category: 'China' },
  { name: 'Soul VIP', slug: 'soul', category: 'China' },
  { name: '脉脉会员', slug: 'maimai', category: 'China' },
  { name: '原神月卡/纪行', slug: 'genshin', category: 'China' },
  { name: '崩坏星穹铁道', slug: 'honkaistarrail', category: 'China' },
  { name: '王者荣耀战令', slug: 'wangzhe', category: 'China' },
  { name: '和平精英精英手册', slug: 'pubgm', category: 'China' },
  { name: '腾讯心悦会员', slug: 'xinyue', category: 'China' },
  { name: '文心一言', slug: 'wenxin', category: 'China' },
  { name: '通义千问', slug: 'tongyi', category: 'China' },
  { name: '讯飞星火', slug: 'xunfei', category: 'China' },
  { name: '豆包', slug: 'doubao', category: 'China' },
  { name: 'Kimi', slug: 'kimi', category: 'China' },
  { name: '智谱清言', slug: 'zhipu', category: 'China' },
  { name: '腾讯元宝', slug: 'yuanbao', category: 'China' },
  { name: '同花顺', slug: 'tonghuashun', category: 'China' },
  { name: '东方财富', slug: 'eastmoney', category: 'China' },
  { name: '雪球', slug: 'xueqiu', category: 'China' },
  { name: 'Keep 会员', slug: 'keep', category: 'China' },
  { name: '薄荷健康', slug: 'bohe', category: 'China' },
  { name: '丁香医生', slug: 'dxy', category: 'China' },
  { name: '春雨医生', slug: 'chunyuyisheng', category: 'China' },
  { name: '极客时间', slug: 'geektime', category: 'China' },
  { name: '掘金小册', slug: 'juejin', category: 'China' },
  { name: 'CSDN 会员', slug: 'csdn', category: 'China' },
  { name: '慕课网', slug: 'imooc', category: 'China' },
  { name: '中国大学MOOC', slug: 'icourse', category: 'China' },
  { name: '知识星球', slug: 'zsxq', category: 'China' },
  { name: '小鹅通', slug: 'xiaoe', category: 'China' },
  { name: '千聊', slug: 'qianliao', category: 'China' },
  { name: '飞书 (Lark)', slug: 'feishu', category: 'China' },
  { name: '钉钉 (DingTalk)', slug: 'dingtalk', category: 'China' },
  { name: '企业微信', slug: 'wechatwork', category: 'China' },
  { name: '虎牙', slug: 'huya', category: 'China' },
  { name: '斗鱼', slug: 'douyu', category: 'China' },
  { name: '视觉中国', slug: 'vcg', category: 'China' },
  { name: '小红书', slug: 'xiaohongshu', category: 'China' },
  { name: '抖音', slug: 'douyin', category: 'China' },
  { name: '快手', slug: 'kuaishou', category: 'China' },

  // --- Japan ---
  { name: 'U-NEXT', slug: 'unext', category: 'Japan', defaultPrice: 218900, defaultCurrency: 'JPY' },
  { name: 'Hulu Japan', slug: 'hulu', category: 'Japan' },
  { name: 'Lemino', slug: 'lemino', category: 'Japan' },
  { name: 'ABEMA', slug: 'abema', category: 'Japan' },
  { name: 'FOD', slug: 'fod', category: 'Japan' },
  { name: 'TELASA', slug: 'telasa', category: 'Japan' },
  { name: 'WOWOW', slug: 'wowow', category: 'Japan' },
  { name: 'DMM TV', slug: 'dmm', category: 'Japan' },
  { name: 'd Anime Store', slug: 'danimestore', category: 'Japan' },
  { name: 'NHK オンデマンド', slug: 'nhk', category: 'Japan' },
  { name: 'TVer', slug: 'tver', category: 'Japan' },
  { name: 'DAZN Japan', slug: 'dazn', category: 'Japan' },
  { name: 'LINE Music', slug: 'linemusic', category: 'Japan', defaultPrice: 98000, defaultCurrency: 'JPY' },
  { name: 'AWA', slug: 'awa', category: 'Japan' },
  { name: 'Rakuten Music', slug: 'rakutenmusic', category: 'Japan' },
  { name: 'dヒッツ', slug: 'dhits', category: 'Japan' },
  { name: 'Kindle Unlimited JP', slug: 'amazon', category: 'Japan' },
  { name: 'dマガジン', slug: 'dmagazine', category: 'Japan' },
  { name: '楽天マガジン', slug: 'rakuten', category: 'Japan' },
  { name: 'コミックシーモア', slug: 'comicseymour', category: 'Japan' },
  { name: 'まんが王国', slug: 'mangaoukoku', category: 'Japan' },
  { name: 'BookLive', slug: 'booklive', category: 'Japan' },
  { name: 'ピッコマ Piccoma', slug: 'piccoma', category: 'Japan' },
  { name: 'LINEマンガ', slug: 'linemanga', category: 'Japan' },
  { name: 'ジャンプ+', slug: 'shonenjump', category: 'Japan' },
  { name: 'マガポケ', slug: 'magapocket', category: 'Japan' },
  { name: 'BOOK WALKER', slug: 'bookwalker', category: 'Japan' },
  { name: 'Amazon Prime Japan', slug: 'amazon', category: 'Japan', defaultPrice: 60000, defaultCurrency: 'JPY' },
  { name: '楽天プレミアム', slug: 'rakuten', category: 'Japan' },
  { name: 'Yahoo! プレミアム', slug: 'yahoo', category: 'Japan' },
  { name: '食べログ Premium', slug: 'tabelog', category: 'Japan' },
  { name: 'Cookpad Premium', slug: 'cookpad', category: 'Japan' },
  { name: 'Pixiv FANBOX', slug: 'pixiv', category: 'Japan' },
  { name: 'Fantia', slug: 'fantia', category: 'Japan' },
  { name: 'ci-en', slug: 'cien', category: 'Japan' },
  { name: 'SHOWROOM', slug: 'showroom', category: 'Japan' },
  { name: 'Pococha', slug: 'pococha', category: 'Japan' },
  { name: '17LIVE', slug: '17live', category: 'Japan' },
  { name: 'note', slug: 'note', category: 'Japan' },
  { name: 'Voicy', slug: 'voicy', category: 'Japan' },
  { name: 'Niconico', slug: 'niconico', category: 'Japan' },
  { name: '日経電子版', slug: 'nikkei', category: 'Japan' },
  { name: 'Fate/Grand Order', slug: 'fategrandorder', category: 'Japan' },
  { name: 'Uma Musume', slug: 'umamusume', category: 'Japan' },

  // --- Korea ---
  { name: 'Wavve', slug: 'wavve', category: 'Korea' },
  { name: 'Tving', slug: 'tving', category: 'Korea' },
  { name: 'Watcha', slug: 'watcha', category: 'Korea' },
  { name: 'Coupang Play', slug: 'coupang', category: 'Korea' },
  { name: 'Laftel', slug: 'laftel', category: 'Korea' },
  { name: 'CHZZK', slug: 'chzzk', category: 'Korea' },
  { name: 'Melon', slug: 'melon', category: 'Korea' },
  { name: 'Genie Music', slug: 'geniemusic', category: 'Korea' },
  { name: 'Bugs', slug: 'bugs', category: 'Korea' },
  { name: 'FLO', slug: 'flo', category: 'Korea' },
  { name: 'Vibe', slug: 'vibe', category: 'Korea' },
  { name: 'Naver Webtoon', slug: 'naver', category: 'Korea' },
  { name: 'Kakao Page', slug: 'kakao', category: 'Korea' },
  { name: 'Lezhin Comics', slug: 'lezhin', category: 'Korea' },
  { name: 'Toomics', slug: 'toomics', category: 'Korea' },
  { name: 'Ridi', slug: 'ridi', category: 'Korea' },
  { name: '밀리의 서재 Millie', slug: 'millie', category: 'Korea' },
  { name: 'Coupang Rocket WOW', slug: 'coupang', category: 'Korea', defaultPrice: 499000, defaultCurrency: 'KRW' },
  { name: 'Naver Plus Membership', slug: 'naver', category: 'Korea' },
  { name: 'Market Kurly', slug: 'kurly', category: 'Korea' },
  { name: '배달의민족 Baemin', slug: 'baemin', category: 'Korea' },
  { name: '요기요 Yogiyo', slug: 'yogiyo', category: 'Korea' },
  { name: 'Toss', slug: 'toss', category: 'Korea' },
  { name: 'Kakao Pay', slug: 'kakaopay', category: 'Korea' },
  { name: 'Weverse', slug: 'weverse', category: 'Korea' },
  { name: 'Bubble / Dear U', slug: 'dearu', category: 'Korea' },
  { name: 'afreecaTV', slug: 'afreecatv', category: 'Korea' },
  { name: 'Spoon', slug: 'spoon', category: 'Korea' },
  { name: 'Pairs', slug: 'pairs', category: 'Korea' },
  { name: 'Omiai', slug: 'omiai', category: 'Korea' },

  // --- India ---
  { name: 'JioCinema', slug: 'jiocinema', category: 'India' },
  { name: 'Netflix India', slug: 'netflix', category: 'India' },
  { name: 'Disney+ Hotstar', slug: 'hotstar', category: 'India' },
  { name: 'ZEE5', slug: 'zee5', category: 'India' },
  { name: 'SonyLIV', slug: 'sonyliv', category: 'India' },
  { name: 'ALTBalaji', slug: 'altbalaji', category: 'India' },
  { name: 'Aha', slug: 'aha', category: 'India' },
  { name: 'Sun NXT', slug: 'sunnxt', category: 'India' },
  { name: 'Hoichoi', slug: 'hoichoi', category: 'India' },
  { name: 'ShemarooMe', slug: 'shemaroome', category: 'India' },
  { name: 'Airtel Xstream', slug: 'airtel', category: 'India' },
  { name: 'Amazon Prime India', slug: 'amazon', category: 'India' },
  { name: 'Flipkart Plus', slug: 'flipkart', category: 'India' },
  { name: 'Myntra Insider', slug: 'myntra', category: 'India' },
  { name: 'Tata Neu', slug: 'tata', category: 'India' },
  { name: 'BigBasket', slug: 'bigbasket', category: 'India' },
  { name: 'Blinkit', slug: 'blinkit', category: 'India' },
  { name: 'Zepto', slug: 'zepto', category: 'India' },
  { name: 'Swiggy One', slug: 'swiggy', category: 'India' },
  { name: 'Zomato Gold', slug: 'zomato', category: 'India' },
  { name: "Byju's", slug: 'byjus', category: 'India' },
  { name: 'Unacademy', slug: 'unacademy', category: 'India' },
  { name: 'Vedantu', slug: 'vedantu', category: 'India' },
  { name: 'PhysicsWallah', slug: 'physicswallah', category: 'India' },
  { name: 'upGrad', slug: 'upgrad', category: 'India' },
  { name: 'Simplilearn', slug: 'simplilearn', category: 'India' },
  { name: 'Scaler', slug: 'scaler', category: 'India' },
  { name: 'Zerodha', slug: 'zerodha', category: 'India' },
  { name: 'Groww', slug: 'groww', category: 'India' },
  { name: 'Upstox', slug: 'upstox', category: 'India' },
  { name: 'ET Prime', slug: 'etprime', category: 'India' },
  { name: 'Moneycontrol Pro', slug: 'moneycontrol', category: 'India' },
  { name: 'Practo', slug: 'practo', category: 'India' },
  { name: '1mg', slug: '1mg', category: 'India' },
  { name: 'PharmEasy', slug: 'pharmeasy', category: 'India' },
  { name: 'Cult.fit', slug: 'cultfit', category: 'India' },
  { name: 'HealthifyMe', slug: 'healthifyme', category: 'India' },
  { name: 'The Ken', slug: 'theken', category: 'India' },
  { name: 'JioSaavn Pro', slug: 'jiosaavn', category: 'India' },

  // --- Southeast Asia ---
  { name: 'WeTV', slug: 'wetv', category: 'SoutheastAsia' },
  { name: 'Vidio', slug: 'vidio', category: 'SoutheastAsia' },
  { name: 'meWATCH', slug: 'mewatch', category: 'SoutheastAsia' },
  { name: 'Astro', slug: 'astro', category: 'SoutheastAsia' },
  { name: 'TrueID', slug: 'trueid', category: 'SoutheastAsia' },
  { name: 'VieON', slug: 'vieon', category: 'SoutheastAsia' },
  { name: 'iWantTFC', slug: 'iwanttfc', category: 'SoutheastAsia' },
  { name: 'VivaMax', slug: 'vivamax', category: 'SoutheastAsia' },
  { name: 'Catchplay+', slug: 'catchplay', category: 'SoutheastAsia' },
  { name: 'KKTV', slug: 'kktv', category: 'SoutheastAsia' },
  { name: 'myVideo', slug: 'myvideo', category: 'SoutheastAsia' },
  { name: 'myTV SUPER', slug: 'mytvsuper', category: 'SoutheastAsia' },
  { name: 'Grab', slug: 'grab', category: 'SoutheastAsia' },
  { name: 'Gojek', slug: 'gojek', category: 'SoutheastAsia' },
  { name: 'GoTo', slug: 'goto', category: 'SoutheastAsia' },
  { name: 'Shopee', slug: 'shopee', category: 'SoutheastAsia' },
  { name: 'Lazada', slug: 'lazada', category: 'SoutheastAsia' },
  { name: 'Tokopedia', slug: 'tokopedia', category: 'SoutheastAsia' },
  { name: 'GrabPay', slug: 'grabpay', category: 'SoutheastAsia' },
  { name: 'GoPay', slug: 'gopay', category: 'SoutheastAsia' },
  { name: 'OVO', slug: 'ovo', category: 'SoutheastAsia' },
  { name: 'Dana', slug: 'dana', category: 'SoutheastAsia' },
  { name: 'ShopeePay', slug: 'shopeepay', category: 'SoutheastAsia' },
  { name: "Touch'n Go", slug: 'touchngo', category: 'SoutheastAsia' },
  { name: 'GCash', slug: 'gcash', category: 'SoutheastAsia' },
  { name: 'Maya', slug: 'maya', category: 'SoutheastAsia' },
  { name: 'MoMo', slug: 'momo', category: 'SoutheastAsia' },
  { name: 'ZaloPay', slug: 'zalopay', category: 'SoutheastAsia' },
  { name: 'TrueMoney', slug: 'truemoney', category: 'SoutheastAsia' },
  { name: 'GrabFood', slug: 'grab', category: 'SoutheastAsia' },
  { name: 'GoFood', slug: 'gojek', category: 'SoutheastAsia' },
  { name: 'ShopeeFood', slug: 'shopee', category: 'SoutheastAsia' },
  { name: 'LINE Man', slug: 'line', category: 'SoutheastAsia' },
  { name: 'Deliveroo Singapore', slug: 'deliveroo', category: 'SoutheastAsia' },
  { name: 'Straits Times', slug: 'straitstimes', category: 'SoutheastAsia' },

  // --- Latin America ---
  { name: 'Globoplay', slug: 'globoplay', category: 'LatinAmerica' },
  { name: 'ViX', slug: 'vix', category: 'LatinAmerica' },
  { name: 'Claro Video', slug: 'clarovideo', category: 'LatinAmerica' },
  { name: 'Blim TV', slug: 'blimtv', category: 'LatinAmerica' },
  { name: 'Flow', slug: 'flow', category: 'LatinAmerica' },
  { name: 'Rappi', slug: 'rappi', category: 'LatinAmerica' },
  { name: 'iFood', slug: 'ifood', category: 'LatinAmerica' },
  { name: 'Mercado Libre', slug: 'mercadolibre', category: 'LatinAmerica' },
  { name: 'Nubank', slug: 'nubank', category: 'LatinAmerica' },
  { name: 'PicPay', slug: 'picpay', category: 'LatinAmerica' },

  // --- Middle East ---
  { name: 'Shahid VIP', slug: 'shahid', category: 'MiddleEast' },
  { name: 'OSN+', slug: 'osn', category: 'MiddleEast' },
  { name: 'TOD', slug: 'tod', category: 'MiddleEast' },
  { name: 'StarzPlay Arabia', slug: 'starzplay', category: 'MiddleEast' },
  { name: 'Careem', slug: 'careem', category: 'MiddleEast' },

  // --- Africa ---
  { name: 'Showmax', slug: 'showmax', category: 'Africa' },
  { name: 'DStv', slug: 'dstv', category: 'Africa' },
  { name: 'Canal+ Afrique', slug: 'canalplus', category: 'Africa' },
  { name: 'StarTimes', slug: 'startimes', category: 'Africa' },
  { name: 'IROKOtv', slug: 'irokotv', category: 'Africa' },
  { name: 'M-Pesa', slug: 'mpesa', category: 'Africa' },

  // --- Russia/Eastern Europe ---
  { name: 'Kinopoisk', slug: 'kinopoisk', category: 'Russia' },
  { name: 'IVI', slug: 'ivi', category: 'Russia' },
  { name: 'Okko', slug: 'okko', category: 'Russia' },
  { name: 'START', slug: 'start', category: 'Russia' },
  { name: 'Premier', slug: 'premier', category: 'Russia' },
  { name: 'Yandex Music', slug: 'yandexmusic', category: 'Russia' },
  { name: 'VK Music', slug: 'vk', category: 'Russia' },
  { name: 'Ozon Premium', slug: 'ozon', category: 'Russia' },
  { name: 'Wildberries', slug: 'wildberries', category: 'Russia' },
  { name: 'Allegro Smart', slug: 'allegro', category: 'Russia' },
]

export const CATEGORIES = [...new Set(POPULAR_SERVICES.map((s) => s.category))]
