import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js'
import type { PgliteDatabase } from 'drizzle-orm/pglite'
import { sql } from 'drizzle-orm'
import * as schema from './schema'

type Db =
  | PostgresJsDatabase<typeof schema>
  | PgliteDatabase<typeof schema>

/**
 * Normalize the shape returned by `db.execute()`. postgres-js returns an
 * array; pglite returns `{ rows }`. We don't want callers to care.
 */
function rowsFrom<T = unknown>(result: unknown): T[] {
  if (Array.isArray(result)) return result as T[]
  if (
    result &&
    typeof result === 'object' &&
    'rows' in result &&
    Array.isArray((result as { rows: unknown[] }).rows)
  ) {
    return (result as { rows: T[] }).rows
  }
  return []
}

/**
 * Run migrations on a Postgres database. Idempotent: safe to call on every
 * boot. Each CREATE TABLE / CREATE INDEX is executed as its own statement
 * because Drizzle's extended-query protocol does not support multi-statement
 * SQL.
 */
export async function migrate(db: Db): Promise<void> {
  const ddl: string[] = [
    `CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      google_id TEXT UNIQUE,
      avatar TEXT,
      preferred_currency TEXT NOT NULL DEFAULT 'CNY',
      monthly_budget INTEGER,
      display_name TEXT,
      show_email BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TEXT NOT NULL DEFAULT (now()::text)
    )`,
    // Migration from password auth → Google OAuth
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS google_id TEXT UNIQUE`,
    `ALTER TABLE users DROP COLUMN IF EXISTS password_hash`,
    `CREATE TABLE IF NOT EXISTS categories (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      icon TEXT,
      user_id INTEGER REFERENCES users(id)
    )`,
    `CREATE TABLE IF NOT EXISTS groups (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      public_id TEXT NOT NULL UNIQUE,
      created_by INTEGER NOT NULL REFERENCES users(id),
      default_currency TEXT NOT NULL DEFAULT 'CNY',
      created_at TEXT NOT NULL DEFAULT (now()::text)
    )`,
    `CREATE TABLE IF NOT EXISTS group_members (
      group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id),
      joined_at TEXT NOT NULL DEFAULT (now()::text),
      PRIMARY KEY (group_id, user_id)
    )`,
    `CREATE TABLE IF NOT EXISTS subscriptions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      logo TEXT,
      url TEXT,
      notes TEXT,
      price INTEGER NOT NULL,
      currency TEXT NOT NULL DEFAULT 'CNY',
      next_payment TEXT NOT NULL,
      start_date TEXT NOT NULL,
      auto_renew BOOLEAN NOT NULL DEFAULT TRUE,
      inactive BOOLEAN NOT NULL DEFAULT FALSE,
      category_id INTEGER REFERENCES categories(id),
      owner_id INTEGER NOT NULL REFERENCES users(id),
      payer_id INTEGER NOT NULL REFERENCES users(id),
      group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE,
      notify BOOLEAN NOT NULL DEFAULT TRUE,
      notify_days_before INTEGER NOT NULL DEFAULT 3,
      refund_policy TEXT NOT NULL DEFAULT 'payer_absorbs',
      tags JSONB NOT NULL DEFAULT '[]'::jsonb,
      created_at TEXT NOT NULL DEFAULT (now()::text)
    )`,
    `ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS refund_policy TEXT NOT NULL DEFAULT 'payer_absorbs'`,
    `ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '[]'::jsonb`,
    // Enforce enum at the DB level so out-of-band writes can't land an
    // invalid value (app-layer Zod + TS casts would lie).
    `DO $$
     BEGIN
       IF NOT EXISTS (
         SELECT 1 FROM pg_constraint
         WHERE conname = 'subscriptions_refund_policy_valid'
       ) THEN
         ALTER TABLE subscriptions
         ADD CONSTRAINT subscriptions_refund_policy_valid
         CHECK (refund_policy IN ('payer_absorbs', 'redistribute'));
       END IF;
     END $$`,
    `CREATE TABLE IF NOT EXISTS billing_records (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      subscription_id INTEGER NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id),
      amount INTEGER NOT NULL,
      currency TEXT NOT NULL,
      local_amount INTEGER NOT NULL,
      local_currency TEXT NOT NULL,
      exchange_rate INTEGER NOT NULL,
      billing_date TEXT NOT NULL,
      is_paid BOOLEAN NOT NULL DEFAULT FALSE,
      paid_at TEXT,
      created_at TEXT NOT NULL DEFAULT (now()::text),
      UNIQUE(subscription_id, user_id, billing_date)
    )`,
    `CREATE TABLE IF NOT EXISTS subscription_members (
      subscription_id INTEGER NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id),
      added_at TEXT NOT NULL,
      added_by INTEGER NOT NULL REFERENCES users(id),
      left_at TEXT,
      PRIMARY KEY (subscription_id, user_id)
    )`,
    `CREATE INDEX IF NOT EXISTS sub_members_by_sub
      ON subscription_members(subscription_id)`,
    `CREATE TABLE IF NOT EXISTS friendships (
      user_a_id INTEGER NOT NULL REFERENCES users(id),
      user_b_id INTEGER NOT NULL REFERENCES users(id),
      created_at TEXT NOT NULL DEFAULT (now()::text),
      agreed_currency_a TEXT,
      agreed_currency_b TEXT,
      PRIMARY KEY (user_a_id, user_b_id),
      CONSTRAINT friendships_ordered CHECK (user_a_id < user_b_id)
    )`,
    // Idempotent ALTERs for existing DBs created before agreed_currency cols.
    `ALTER TABLE friendships ADD COLUMN IF NOT EXISTS agreed_currency_a TEXT`,
    `ALTER TABLE friendships ADD COLUMN IF NOT EXISTS agreed_currency_b TEXT`,
    `CREATE TABLE IF NOT EXISTS notifications (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id),
      type TEXT NOT NULL,
      subscription_id INTEGER REFERENCES subscriptions(id) ON DELETE CASCADE,
      payload TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (now()::text),
      read_at TEXT
    )`,
    `CREATE INDEX IF NOT EXISTS notif_user_unread
      ON notifications(user_id, read_at)`,
    `CREATE TABLE IF NOT EXISTS circles (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      owner_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      default_payer_id INTEGER REFERENCES users(id),
      created_at TEXT NOT NULL DEFAULT (now()::text)
    )`,
    `CREATE INDEX IF NOT EXISTS circles_by_owner ON circles(owner_user_id)`,
    `CREATE TABLE IF NOT EXISTS circle_members (
      circle_id INTEGER NOT NULL REFERENCES circles(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      added_at TEXT NOT NULL DEFAULT (now()::text),
      PRIMARY KEY (circle_id, user_id)
    )`,
    `CREATE TABLE IF NOT EXISTS invites (
      token TEXT PRIMARY KEY,
      subscription_id INTEGER NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
      inviter_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires_at TEXT NOT NULL,
      max_uses INTEGER NOT NULL DEFAULT 1,
      used_count INTEGER NOT NULL DEFAULT 0,
      revoked_at TEXT,
      created_at TEXT NOT NULL DEFAULT (now()::text)
    )`,
    `CREATE INDEX IF NOT EXISTS invites_by_sub ON invites(subscription_id)`,
  ]

  for (const stmt of ddl) {
    await db.execute(sql.raw(stmt))
  }

  // Seed default categories with fixed IDs.
  await db.execute(sql`
    INSERT INTO categories (id, name, icon) VALUES
      (1, 'Entertainment', '🎬'),
      (2, 'Music', '🎵'),
      (3, 'Productivity', '⚡'),
      (4, 'Cloud Storage', '☁️'),
      (5, 'AI Tools', '🤖'),
      (6, 'Gaming', '🎮'),
      (7, 'Education', '📚'),
      (8, 'Other', '📦')
    ON CONFLICT (id) DO NOTHING
  `)

  // Bump the identity sequence past the seeded fixed IDs.
  await db.execute(sql`
    SELECT setval(
      pg_get_serial_sequence('categories', 'id'),
      GREATEST((SELECT MAX(id) FROM categories), 1)
    )
  `)

  // H1 guard — warn on subscriptions with unresolved payer_id instead of
  // refusing to boot. Throwing here blocks every cold start until the data
  // is manually repaired, which is operationally painful; a warning lets
  // the app come up so an admin can actually fix the rows via the UI.
  const orphans = await db.execute(sql`
    SELECT id FROM subscriptions WHERE payer_id IS NULL LIMIT 5
  `)
  const orphanRows = rowsFrom<{ id: number }>(orphans)
  if (orphanRows.length > 0) {
    const ids = orphanRows.map((o) => o.id).join(', ')
    console.warn(
      `[migrate] WARNING subscriptions with unresolved payer_id: ${ids}. ` +
        `Billing for these subs will be skipped until the rows are repaired.`
    )
  }
}

/**
 * T15 — backfill subscription_members and friendships from legacy
 * groups/group_members structures. Idempotent.
 */
export async function backfillFromGroups(db: Db): Promise<number> {
  const today = new Date().toISOString().slice(0, 10)

  const sharedResult = await db.execute(sql`
    INSERT INTO subscription_members
      (subscription_id, user_id, added_at, added_by)
    SELECT s.id,
           gm.user_id,
           COALESCE(gm.joined_at, ${today}),
           g.created_by
    FROM subscriptions s
    INNER JOIN groups g ON g.id = s.group_id
    INNER JOIN group_members gm ON gm.group_id = g.id
    ON CONFLICT (subscription_id, user_id) DO NOTHING
    RETURNING subscription_id AS id
  `)
  const sharedInserted = rowsFrom(sharedResult).length

  const orphanResult = await db.execute(sql`
    INSERT INTO subscription_members
      (subscription_id, user_id, added_at, added_by)
    SELECT s.id,
           s.owner_id,
           COALESCE(s.start_date, ${today}),
           s.owner_id
    FROM subscriptions s
    WHERE s.group_id IS NULL
      AND NOT EXISTS (
        SELECT 1 FROM subscription_members m WHERE m.subscription_id = s.id
      )
    ON CONFLICT (subscription_id, user_id) DO NOTHING
    RETURNING subscription_id AS id
  `)
  const orphanInserted = rowsFrom(orphanResult).length

  await db.execute(sql`
    INSERT INTO friendships (user_a_id, user_b_id, created_at)
    SELECT DISTINCT
      LEAST(g.created_by, gm.user_id),
      GREATEST(g.created_by, gm.user_id),
      ${new Date().toISOString()}
    FROM groups g
    INNER JOIN group_members gm ON gm.group_id = g.id
    WHERE gm.user_id <> g.created_by
    ON CONFLICT (user_a_id, user_b_id) DO NOTHING
  `)

  return sharedInserted + orphanInserted
}
