import { describe, it, expect, beforeEach } from 'vitest'
import { setupTestDb, createUser } from './helpers'
import {
  createSubscription,
  addMemberToSubscription,
  leaveSubscription,
  generateMonthlyBills,
} from '@/lib/db-operations'

/**
 * T8 — R1 monthly cron.
 *
 * On the 1st of month M, for each shared sub, insert one billing_record
 * per active non-payer member: amount = floor(price / memberCount),
 * billing_date = '<M>-01', currency = sub.currency.
 * Payer absorbs rounding remainder (by not being billed).
 * Idempotent: re-running the same month doesn't duplicate.
 */

let db: Awaited<ReturnType<typeof setupTestDb>>['db']
let sqlite: Awaited<ReturnType<typeof setupTestDb>>['sqlite']

beforeEach(async () => {
  const setup = await setupTestDb()
  db = setup.db
  sqlite = setup.sqlite
})

async function allBills(): Promise<Array<{
  subscriptionId: number
  userId: number
  amount: number
  currency: string
  billingDate: string
}>> {
  return (await sqlite.prepare(
    `SELECT subscription_id as "subscriptionId", user_id as "userId",
            amount, currency, billing_date as "billingDate"
     FROM billing_records ORDER BY user_id`
  ).all()) as never
}

/** Bills generated by the R1 monthly cron for a specific month (filter by billing_date). */
async function billsForMonth(yearMonth: string): Promise<Array<{
  subscriptionId: number
  userId: number
  amount: number
  currency: string
  billingDate: string
}>> {
  return (await sqlite.prepare(
    `SELECT subscription_id as "subscriptionId", user_id as "userId",
            amount, currency, billing_date as "billingDate"
     FROM billing_records WHERE billing_date = ? ORDER BY user_id`
  ).all(`${yearMonth}-01`)) as never
}

describe('T8 generateMonthlyBills (R1)', () => {
  it('generates one bill per active non-payer member', async () => {
    const a = await createUser(db, { email: 'a@t.com' })
    const b = await createUser(db, { email: 'b@t.com' })
    const c = await createUser(db, { email: 'c@t.com' })
    const sub = await createSubscription(db, {
      name: 'Netflix',
      price: 15000, // ¥150
      currency: 'CNY',
      nextPayment: '2026-06-01',
      startDate: '2026-03-01',
      ownerId: a,
    })
    await addMemberToSubscription(db, {
      subscriptionId: sub.id,
      userId: b,
      addedBy: a,
      addedAt: '2026-03-15',
    })
    await addMemberToSubscription(db, {
      subscriptionId: sub.id,
      userId: c,
      addedBy: a,
      addedAt: '2026-04-01',
    })

    const count = await generateMonthlyBills(db, '2026-05')

    const bills = await billsForMonth('2026-05')
    expect(count).toBe(2)
    expect(bills).toHaveLength(2)

    // n=3 (A,B,C), share = floor(15000/3) = 5000
    for (const bill of bills) {
      expect(bill.subscriptionId).toBe(sub.id)
      expect(bill.amount).toBe(5000)
      expect(bill.currency).toBe('CNY')
      expect(bill.billingDate).toBe('2026-05-01')
      expect(bill.userId).not.toBe(a) // payer excluded
    }
  })

  it('skips members who left before month start', async () => {
    const a = await createUser(db, { email: 'a@t.com' })
    const b = await createUser(db, { email: 'b@t.com' })
    const c = await createUser(db, { email: 'c@t.com' })
    const sub = await createSubscription(db, {
      name: 'Netflix',
      price: 15000,
      currency: 'CNY',
      nextPayment: '2026-06-01',
      startDate: '2026-03-01',
      ownerId: a,
    })
    await addMemberToSubscription(db, {
      subscriptionId: sub.id,
      userId: b,
      addedBy: a,
      addedAt: '2026-03-15',
    })
    await addMemberToSubscription(db, {
      subscriptionId: sub.id,
      userId: c,
      addedBy: a,
      addedAt: '2026-03-20',
    })
    // B leaves April 20. April 20 < May 1 → B excluded for May billing.
    await leaveSubscription(db, {
      subscriptionId: sub.id,
      userId: b,
      leftAt: '2026-04-20',
    })

    await generateMonthlyBills(db, '2026-05')

    const bills = await billsForMonth('2026-05')
    expect(bills.map((b) => b.userId)).toEqual([c])
    // After B leaves, members = {A, C}. share = floor(15000/2) = 7500.
    expect(bills[0].amount).toBe(7500)
  })

  it('skips members added after month start (R2 covers them)', async () => {
    const a = await createUser(db, { email: 'a@t.com' })
    const b = await createUser(db, { email: 'b@t.com' })
    const sub = await createSubscription(db, {
      name: 'Netflix',
      price: 15000,
      currency: 'CNY',
      nextPayment: '2026-06-01',
      startDate: '2026-03-01',
      ownerId: a,
    })
    // B joins mid-May — not part of May 1 cron.
    await addMemberToSubscription(db, {
      subscriptionId: sub.id,
      userId: b,
      addedBy: a,
      addedAt: '2026-05-15',
    })

    await generateMonthlyBills(db, '2026-05')

    const bills = await billsForMonth('2026-05')
    expect(bills).toHaveLength(0)
  })

  it('is idempotent — running twice for the same month does not duplicate', async () => {
    const a = await createUser(db, { email: 'a@t.com' })
    const b = await createUser(db, { email: 'b@t.com' })
    const sub = await createSubscription(db, {
      name: 'Netflix',
      price: 10000,
      currency: 'CNY',
      nextPayment: '2026-06-01',
      startDate: '2026-03-01',
      ownerId: a,
    })
    await addMemberToSubscription(db, {
      subscriptionId: sub.id,
      userId: b,
      addedBy: a,
      addedAt: '2026-03-10',
    })

    await generateMonthlyBills(db, '2026-05')
    await generateMonthlyBills(db, '2026-05')

    expect(await billsForMonth('2026-05')).toHaveLength(1)
  })

  it('skips personal subs (no group_id AND only one member)', async () => {
    const a = await createUser(db)
    await createSubscription(db, {
      name: 'Spotify',
      price: 1500,
      currency: 'CNY',
      nextPayment: '2026-06-01',
      startDate: '2026-03-01',
      ownerId: a,
    })

    await generateMonthlyBills(db, '2026-05')
    expect(await allBills()).toHaveLength(0)
  })

  it('skips inactive subscriptions', async () => {
    const a = await createUser(db, { email: 'a@t.com' })
    const b = await createUser(db, { email: 'b@t.com' })
    const sub = await createSubscription(db, {
      name: 'Netflix',
      price: 10000,
      currency: 'CNY',
      nextPayment: '2026-06-01',
      startDate: '2026-03-01',
      ownerId: a,
    })
    await addMemberToSubscription(db, {
      subscriptionId: sub.id,
      userId: b,
      addedBy: a,
      addedAt: '2026-03-10',
    })
    await sqlite.prepare('UPDATE subscriptions SET inactive = true WHERE id = ?')
      .run(sub.id)

    await generateMonthlyBills(db, '2026-05')
    expect(await billsForMonth('2026-05')).toHaveLength(0)
  })

  it('stores local_amount in each member preferred currency', async () => {
    const a = await createUser(db, { email: 'a@t.com', currency: 'USD' })
    const b = await createUser(db, { email: 'b@t.com', currency: 'CNY' })
    const sub = await createSubscription(db, {
      name: 'Netflix',
      price: 1500, // $15.00 USD
      currency: 'USD',
      nextPayment: '2026-06-01',
      startDate: '2026-03-01',
      ownerId: a,
    })
    await addMemberToSubscription(
      db,
      {
        subscriptionId: sub.id,
        userId: b,
        addedBy: a,
        addedAt: '2026-03-10',
      },
      { USD_CNY: 7.2 }
    )

    await generateMonthlyBills(db, '2026-05', { USD_CNY: 7.2 })

    const row = await sqlite.prepare(
        `SELECT local_amount, local_currency FROM billing_records WHERE billing_date = '2026-05-01'`
      )
      .get() as { local_amount: number; local_currency: string }
    // share = floor(1500/2) = 750 cents. 750 * 7.2 = 5400.
    expect(row.local_amount).toBe(5400)
    expect(row.local_currency).toBe('CNY')
  })
})
